apache/cassandra-gocql-driver

cassandra_test.go, session.go
Iter.MapScan(map[string]interface{}) Method is an useful interface to imprement data bindings.
It would be nice if *Query also has this method.
Could you review this PR?
=> Add func (*Query)MapScan(map[string]interface{})

.travis.yml, README.md
This just sets the current Travis build version to 2.1.2 on the 2.1.x series.
=> Upgrade CI build to Cassandra 2.1.2

AUTHORS, cluster.go
This is intended to make it easy to set a default PageSize for all CQL sessions that share the same configuration.
Looked like a pretty trivial change. Hopefully doesn't violate project philosophy or anything :smirk:
=> Added PageSize as a property for ClusterConfig

AUTHORS, cassandra_test.go, cluster.go, conn.go
Previously, the only way to establish the *first* connection was to use `ClusterConfig.CreateSession()`. This is due to the global prepared statement cache only being initialised here.
=> Fix a panic establishing sessions using NewSession

helpers.go, marshal_test.go
There are a few bugs in the way that we resolve Apache Cassandra internal type names:
* TimestampType (successor to DateType) has no support - so we need to add this
* Sets and Lists were being incorrectly mapped to the inet type (as pointed out by @justinretailnext as part of #309)
So this patch attempts to clean up these errors irrespective of the development of #309.
=> Fix bugs in Cassandra internal type resolution

connectionpool.go
This patches a bug whereby a closed pool could be refilled during a race condition. It also makes access the the `quit` flag more consistent with other access paths.
=> lock mu when checking if the pool is closed

AUTHORS, cassandra_test.go, marshal.go, metadata.go, metadata_test.go, session.go
Adds a function to get the schema metadata from a Session for the session's current keyspace. Also includes a couple typo fixes in the TypeInfo code.
The implementation is based on the [DataStax Java Driver](https://github.com/datastax/java-driver), specifically the code found in these Java classes:
* [ControlConnection.java](https://github.com/datastax/java-driver/blob/2.1/driver-core/src/main/java/com/datastax/driver/core/ControlConnection.java)
* [Metadata.java](https://github.com/datastax/java-driver/blob/2.1/driver-core/src/main/java/com/datastax/driver/core/Metadata.java)
* [KeyspaceMetadata.java](https://github.com/datastax/java-driver/blob/2.1/driver-core/src/main/java/com/datastax/driver/core/KeyspaceMetadata.java)
* [TableMetadata.java](https://github.com/datastax/java-driver/blo …
=> Adds a function to retrieve schema metadata of the session's keyspace

session.go
I'm not 100% sure whether this is technically a bug or not (please close if not), but it seems to me that when constructing a `Session` with `NewSession`, its consistency level should be defaulted to that of its `ClusterConfig`.
=> Default a Session's consistency to that of its ClusterConfig

cassandra_test.go, cluster.go, metadata.go, session.go
This PR adds some incremental functionality which would be needed for token awareness in a connection pool. It depends on the metadata functionality from my previous PR. Since gocql doesn't differentiate between prepared and unprepared statements, this functionality is a departure in some respects from the Datastax driver methodology, which it is loosely based on.
The top-level functionality added in this PR is the addition of the `GetRoutingKey() []byte` function to `Query`. This function returns the computed routing key for a given statement and its bound values. The function `RoutingKey([]byte)` is supplied in `Query` as a way to override the routing key, or as a simple short circuit to avoid the computation of the routing key (e.g. cqlc could probably generate code that creates …
=> Added routing key computation to Query

integration.sh
Simplify how the cluster config is setup using ccm.
Pass an absolute path for the keystore, fixes #345
=> Simplify cluster config

cluster.go, conn.go, connectionpool.go, session_test.go
we can reuse the TLS Config between connections, so avoid the
expensive read and cert parsing when dialing connections, instead
do this in the connection pool once during startup.
=> conn: only setup the TLS config once

token.go, token_test.go
This PR adds implementations of token partitioners for the 3 cassandra partitioning strategies as well as a token ring implementation. These implementations are mostly based on the DataStax cassandra drivers, with some references to the cassandra codebase itself. My original Murmur3Token implementation depended on github.com/spaolacci/murmur3 package, though since the DataStax driver includes the murmur3 algorithm in its implementation, I though it might be simpler to include the murmur3 implementation here as well and avoid the dependency ; the murmur3 code is based on [MurmurHash3_x64_128 code in the C++ reference implementation](https://code.google.com/p/smhasher/source/browse/trunk/MurmurHash3.cpp#255) along with the [unsafe getblock optimization from the spaolacci murmur3 …
=> Token partitioners and a token ring

integration.sh
I've found that while testing changes locally that these changes simplify running integration.sh.
- Replaced the sed commands with usage of the --jvm_arg parameter of 'ccm create' for GC tuning
- Added 'ccm remove test' command as an optional step to remove the previous test cluster if it
already exists
- Changed the 'ccm clear' command to 'ccm remove'
YMMV, and I understand this is for travis builds too testing so not sure if they're the best generic changes.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/gocql/gocql/349)
=> Enhancements to integration.sh for ease-of-use in development

README.md, cassandra_test.go, conn.go, conn_test.go, errors.go, errors_test.go, frame.go, marshal.go, session.go, session_test.go
Simplify the protocol implementation so that all the logic for handling different protocol versions is now handled inside frame.go. This should make it easier to improve and change the protocols going forward without having to make lots of changes elsewhere.
=> refactor all framing protocol code into frame

frame.go
In v3 the stream is an int16 not a uint16, int v2 ensure we handle
the sign of the int8 correctly.
=> Fix reading the streamID sign

cassandra_test.go, cluster.go, conn.go, frame.go, session.go, session_test.go
Add an option to Query to set the serial consistency for the
conditional update phase of a query.
closes #343
=> Add with serial consistency support

cassandra_test.go
Fixes a race condition when checking items inside the prepared
statement cache during tests.
=> LRU Get and Len are not thread safe

cassandra_test.go, frame.go
A batch must always set the number of values even if the statement
is not prepraed and has no values, such is the case when using
counters.
Fixes #364
=> Always set the number of values in a batch

session.go
When creating a batch from a session, inherit the consistency from
the session.
Fixes #355
=> Inherit consistency from session in NewBatch

frame.go, marshal.go, session.go, udt_test.go
Add support to read and write UDT's at the framing and scanning level.
To scan or marshal a UDT type the type must implement the Marshal/
UnmarshalUDT type.
Fixes #175
=> Add support for UDT's

session.go
If there is no routing key available then the function will
return `nil, nil` and release the waitgroup. The waiters will
then type assert `inflight.value` which is a nil interface
value which then panics. In this case we should just return
nil as the originating function did.
=> ensure that the value asertion does not panic

connectionpool.go
This fixes a test flake which expects that when creating a pool returns
that it has the correct number of connections in it, which is not the
case for the Policy based pool which will connect a single connection
synchronously then do the rest async. Change it so that it now when
doing an initial fill will do the whole fill synchronously.
=> When initially filling the host pool do it sync.

conn.go
When using tls we should set timeouts when dialing to prevent
blocking indefintely on downed hosts.
=> Use timeouts when dialing tls sockets

cluster.go, session.go, session_test.go
CreateSession on the cluster config is a helper method to setup
defaults for the session, but it also does a lot of the setup, such
as creating the connection pool and creating the host discovery
goroutine.
Move all this logic into NewSession so that CreateSession now just
returns NewSession.
=> Consolidate new session

policies.go
When the policy is checking the length of the host list in
roundRobinHostPolicy ensure that we hold the read lock so that
if SetHosts is called we dont data race.
=> Ensure we hold a read lock to check hosts

connectionpool.go
If the host is down and its connect blocks until timeout the
caller should not be blocked because it may be coming from a call
to execute a query.
=> When the hostpool is empty dont block in fill

marshal.go, marshal_test.go
Including marshaling typed nils (for example (*CustomString)(nil)).
=> Fixed marshaling of pointer to interface.

marshal.go, udt_test.go
Currently, when marshaling UDTs, the marshaling of the `length` of the UDT's data uses the wrong bit shift order - which prevents UDTs from being larger than 256 bytes. Cassandra returns back with `Invalid remaining data after end of UDT value`.
This PR fixes the shift order, and also provides a test that trigger the big.
=> Fix bitshift order in udt length calculation

marshal.go, udt_test.go
When a UDT column is null it's data will be empty, when this is the
case set the unmarshal target to its zero value if possible and
return.
=> Correctly unmarshal null UDT responses

compressor.go, compressor_test.go
We seem to be getting the following error importing snappy:
```
package code.google.com/p/snappy-go/snappy: unable to detect version control system for code.google.com/ path
```
So this is an attempt to fix this (see #402 for context).
=> Redefine snappy import

AUTHORS, host_source.go, session.go
Currently, when setting 'DiscoverHosts' to 'true', you open up a goroutine that periodically checks for host updates; this goroutine is never cleaned up (goroutine leak) when the session is closed and it will display 'RingDescriber: unable to get ring topology: use of closed network connection' continuously until the program exits.
My pull request adds a channel to 'ringDescriber'; adds a select statement to the 'run' method to check when the channel is closed; 'hostSource' variable is added to 'Session' (I'm not sure if keeping 'Session' agnostic to 'ringDescriber' is important or not); on session close we check to see if 'session.hostSource' is nil, if not, close the 'closeChan' that will clean up the goroutine.
=> Added closeChan to clean up ring describer when session is closed

frame.go, frame_test.go
If the column count for a row result is huge it will trigger either
a makeslice: len out of range or the program will do lots of gc
which make the application unresponsive, even if there are not really
that many columns.
=> Dont allocate all the columninfo upfront

AUTHORS, conn.go, connectionpool.go
The helper functions simply toggle internal state, now, and all the
flexibility of tls.Config is available.
=> Remove limitations of SslOptions by making it inherit from tls.Config.

conn.go, conn_test.go
Start a timeout when waiting for the response from cassandra
in the call to exec() so that if no header is read the query
will not hang for ever.
If there are more than a limit of timeouts then the connection will
be closed. This may need tuning in the future if there are queries
which take a long time.
fixes #416
=> apply a timeout for every query at the connection

AUTHORS, marshal.go, marshal_test.go
This is a fix for the following situation:
```go
type T struct { /* ... */ }
// MarshalCQL implements the gocql.Marshaler interface
func (t *T) MarshalCQL(info TypeInfo) ([]byte, error) {
// ...
}
func laterInTheCode() {
t := &T{ /* ... */ }
data, err := gocql.Marshal(info, t) // <-- won't work
// ...
}
```
`Marshal` resolves a pointer value before checking if it implements the `Marshaler` interface. The code above won’t work because `T` doesn’t implement the `Marshaler` interface, only `*T` does.
I added a test that shows the bug. The test fails without the fix and passes with it.
---
Running `go fmt` on `marshal_test.go` fixes other parts of the code but it polluted the diff so I didn’t include the changes here. Do you want me to include them?
=> Marshal fixed for pointers implementing Marshaler

policies.go
This fixes the indentation of the example code, which was wrongly indented in the online Godoc.
With a local `godoc` server, here’s how it’s now:
And how it’s with this patch:
=> SimpleRetryPolicy doc format fixed

conn.go, conn_test.go
Having a timeout on the query level introduces some very
subtle race condtions which need to be addressed before enabling.
=> remove query level timeouts

conn.go, conn_test.go
Correctly synchronise the response timeout handling between waiting for the response and sending the response back. Improve handling of streams so they are returned in the correct place, ensure that streams are returned always. Improve handling when a connection is closed so queries don't get blocked in exec.
Add a test which timesout on a stream then execute another query before the first query returns which triggers the previous error when reusing streams.
Fixes #426 #417
=> Reinstate query timeouts

conn.go
Buffer the channel which the IO goroutine sends the response
back to the stream handler so that the IO goroutine will not
block waiting for a slow stream handler.
=> buffer the connection response channel

cluster.go
If we do not set default `PageSize` to a reasonable number, the query may cause whole cassandra cluster OOM. The [default page size of cassandra java driver is 5000](http://docs.datastax.com/en/drivers/java/2.0/com/datastax/driver/core/QueryOptions.html#DEFAULT_FETCH_SIZE). 
More information can be found in this issue: https://issues.apache.org/jira/browse/CASSANDRA-9607
=> Set Cluster Default PageSize to 5000

cassandra_test.go, conn.go, stress_test.go
Remove the atomic waiting variable, it can lead to a case
where a stream is released twice which will cause data races
and unforseen panics.
The case this can happen is that in exec the frame is written
and the response is received before call.waiting is set
from 0 to 1. This is most likely down to the runtime scheduling
the recv() io goroutine before the atomic store happens. The recv()
goroutine sees that call.waiting is 0 and assumes that is has timed
out, releasing the stream. Then the exec() goroutine is scheduled
which sets call.waiting to 1 and then blocks in the select waiting
for the response, which never comes so the timeout option is selected
which then releases the stream again.
Solve this by removing the call.waiting synchronisation which was
not protecting anything as the …
=> prevent duplicate stream usage

AUTHORS, marshal.go, marshal_test.go
The `Timestamp` CQL type is represented by a 64bit integer number of ms since the epoch, stored as 8 bytes. Currently marshaling of the `time.Time` type into this uses the `UnixNano()` func, which can only represent times between approximately the years 1677 and 2262 before overflowing.
This means that the zero time (`0001-01-01 00:00:00 +0000 UTC`) can _not_ be represented within this range, as mentioned in the [time pkg documentation](http://golang.org/pkg/time/#Time.UnixNano): _"the result of calling UnixNano on the zero Time is undefined"_. And as a side effect, marshaling a zero time into the cassandra results in a time of approx `1754-08-30 22:43:41.129 +0000 UTC` rather than zero. This is then correctly unmarshalled back out of cassandra, so the data stored does not equal the …
=> Fix timestamp type marshaling

metadata.go, metadata_test.go
In some schemas there may be "partition_key" type columns returned in the V2 protocol metadata which have the same component index; in our case we have a couple column families with aliased columns "KEY" and "key" for historical reasons. When the token-aware connection pool is used with these column families, a nil-pointer panic occurs since the partition key length (column count) was being incorrectly calculated; This change is based on the DataStax driver's behavior for columns with the same component index, which prefers the last column in order defined for that component index; the consequence of this behavior is that other column names defined for the same component index will not be identified as part of a routing key.
Also, "compact_value" has been added as a column kind/type. …
=> Improve support for complicated cassandra schemas.

AUTHORS, cassandra_test.go, helpers.go, marshal.go, marshal_test.go, wiki_test.go
At http://speter.net/ it says that the speter.net/go/exp/math/dec/inf has been replaced by gopkg.in/inf.v0
=> Update deprecated package

conn.go, conn_test.go
If a connection is closed then call to closeWithError will send
the error to the callers resp channel, which the caller in exec
will unblock, release the stream which will set the framer to nil.
Then if the response for that stream comes back from Cassandra into
recv() then the call.framer will be nil and will panic.
Instead of always releasing the stream when getting a reponse from
the channel only do it if there is no error.
Updates #439
=> conn: ensure that call.framer is not nil

cassandra_test.go, conn.go, conn_test.go
If Cassandra has an error and does not honor the protocol and returns
a response on a different stream than the request then the stream will
be 0, this can happen if there is a corrputed frame or an invalid
protocol version.
Detect the responses on stream 0 and cause it to be sent to all
outstanding requests so that they don't block indefinatly, as they may
have caused the original error.
=> conn: dont use stream 0 for outgoing requests

AUTHORS, session.go
To make logging a little nicer in downstream usage.
=> Implement stringer interface for the Query type

AUTHORS, session.go
Benchmark results for a 80 character statement that does not start with
'use':
Before: 1927 ns/op   192 B/op   2 allocs/op
After:  142 ns/op      6 B/op   2 allocs/op
=> query: Improve efficiency of 'USE' statement detection

cluster.go, lru/lru.go, lru/lru_test.go, session.go
Using an LRU cache with interface{} keys means that each lookup is
significantly more expensive than a simple string hash: the string value
first has to be wrapped into an interface{}, causing a memory
allocation, and the map then needs to figure out what's the proper way
to hash that value.
The code is just a copy of github.com/gocql/gocql/lru with the Key type replaced by string.
=> Use an LRU cache with "pure" string keys

session.go, stress_test.go
This speeds up things quite a bit when doing lots of small insert queries against Cassandra, by reducing the load on the garbage collector. I'm not 100% sure about the correctness of "no need to include keyspace in routingKeyInfoCache key", but since the session keyspace seems to be immutable, including it in a map key when the map is per-session doesn't seem needed.
benchcmp (when running with benchtime 30s to let some time for the GC to kick in):
```
benchmark                   old ns/op     new ns/op     delta
BenchmarkConnRoutingKey     654           421           -35.63%
benchmark                   old allocs     new allocs     delta
BenchmarkConnRoutingKey     5              4              -20.00%
benchmark                   old bytes     new bytes     delta
BenchmarkConnRoutingKey …
```
=> Routing key improvements

helpers.go, marshal.go, udt_test.go
Support unmarshalling UDT types into *map[string]interface{} so that they can be used with MapScan.
Fixes #466
=> Add support for MapScan for UDT types

cassandra_test.go, conn.go, session.go
Exposes PageState on the Iter which can then be used to create a new Query which will page from a specific point, disabling automatic page fetching.
Fixes #400
=> Expose page state

cassandra_test.go, helpers.go
Support it by treating it the same as UUIDType.
AFAIK originally there was LexicalUUIDType and TimeUUIDType. Lexical did
simple byte-wise comparison, where Time sorted using the UUID's time
value. UUIDType was added as a convenience type (CASSANDRA-2233) which
compares using the time value for time UUIDs, else byte-wise.
LexicalUUIDType was deprecated but not removed. We still have some
schema around explicitly using the LexicalUUIDType comparator.
=> Add support for "LexicalUUIDType".

AUTHORS, marshal.go, marshal_test.go
Also add unit-tests for tuple marshalling and unmarshalling.
Marshalling tuples is required when tuple is part of collection
(e.g. `set<frozen<tuple<text,text>>>`) and Cassandra doesn't support
placeholders inside collections when parsing queries.
=> Add support for tuple marshalling

cassandra_test.go, conn.go, session.go
I quickly put this together thinking I would need something like ExecuteBatchCAS, and while in the middle of writing the tests, I realized it wouldn't work for the use case I had imagined. 
In any case, this PR adds two functions, `ExecuteBatchCAS` and `MapExecuteBatchCAS`. They function like `ScanCAS`, except they also return an `*Iter` allowing you to read more rows if needed. The `[applied]` column is taken care of in the first function call, but further calls to `.Scan` need to take care of the `applied` column. 
Potentially what we could also do is add a `.ScanCAS` helper function on `*Iter`. What do you guys think?
=> Add ExecuteBatchCAS and MapExecuteBatchCAS functions for using batches with LWT. Fixes #453

AUTHORS, frame.go
Added a function to frame.go that takes a string representation of a Cassandra consistency level and returns the proper gocql constant. If an unrecognized string is provided, it defaults to ALL - when in doubt provide the highest consistency level.
One use case would be when reading the desired Cassandra consistency level from a configuration file.
=> add ParseConsistency() to frame.go

cass1batch_test.go, cassandra_test.go, cluster.go, conn_test.go, connectionpool.go, host_source.go, policies.go, policies_test.go, session.go, session_test.go, stress_test.go
Remove custom pools so that the driver can be simplified and
make more assumptions about the underlying conneciton pool whilst
still allowing configuration of host selection and conn selection policies.
=> Remove SimpleConnPool, remove custom pools

.travis.yml, cassandra_test.go, conn.go, integration.sh
Wait for schema to become consistent across the cluster when
creating tables and keyspaces. Dont export this for now.
Fixes #495
Fixes #422
=> Add method to await for schema to become consistent

cass1batch_test.go, cassandra_test.go, cluster.go, conn.go, conn_test.go, connectionpool.go, control.go, errors_test.go, frame.go, host_source.go, metadata.go, session.go, tuple_test.go, udt_test.go, wiki_test.go
Add a control connection which is used initial for querying
system tables. It will periodically ping the host to ensure
that the connection is alive and reconnect on failures.
Updates #359
=> add internal control connection

cassandra_test.go, control.go, host_source.go, session.go
Cassandra in recent versions added rpc_address to the system.local
table, use this address instead of the connections RemoteAddr()
as we might be behind a proxy.
Updates #481
=> host_source: use system.local rpc_address

AUTHORS, cassandra_test.go, connectionpool.go, control.go, policies.go, policies_test.go, session.go
This PR updates the `HostPolicy` interface to support host pools, more info in #499.
There are some small API changes that were required to allow host status to be reported back to the pool.
=> Update host policies to support host pools, fixes #499

AUTHORS, host_source.go
According to [documentation](http://docs.datastax.com/en/cassandra/2.1/cassandra/configuration/configCassandra_yaml_r.html?scroll=reference_ds_qfg_n1r_1k__start_native_transport), the rpc_address is what should be used
for native transport. We should not use the peer address as the code currently suggest (listen address).
=> Set rpc_address for discovered hosts

control.go
This prevents a panic on calling a `nil` `ringDescriber` when you call `refreshRing`.
=> Refresh ring only if DiscoverHosts is true in control connection

cassandra_test.go, cluster.go, conn.go, connectionpool.go, control.go, session.go, session_test.go
After receiving a schema change frame wait for the cluster schemas
to become consistent.
Move logic for waiting for schema agreement onto Conn, provide
cluster config to change max wait time.
=> wait for schema agreement in conn

frame.go, marshal.go, udt_test.go
When we receive a struct which does not have all the fields for
that UDT then we should encode them as missing values, null on
the wire.
Fixes #515
=> Correctly handle missing UDT fields in Marshal

connectionpool.go, host_source.go, policies.go
- Using broadcast address instead of rpc adress (which might not be unicast IP for client connections)
- Small refactoring of mutex locking
From [Cassandra docs](http://docs.datastax.com/en/cassandra/2.1/cassandra/configuration/configCassandra_yaml_r.html?scroll=reference_ds_qfg_n1r_1k__broadcast_rpc_address):
```
RPC (remote procedure call) settings
Settings for configuring and tuning client connections.
broadcast_rpc_address 
(Default: unset)note RPC address to broadcast to drivers and other Cassandra nodes. This cannot be set to 0.0.0.0. If blank, it is set to the value of the rpc_address or rpc_interface. If rpc_address or rpc_interfaceis set to 0.0.0.0, this property must be set. 
```
Fixes #509
=> Connection pool deadlock / invalid discovery rpc address

conn.go
The conn config is shared by the connection pool.
Updates #519
=> conn: dont mutate the conn config

helpers.go, marshal.go, marshal_test.go, udt_test.go
When a UDT has a missing value or a nil value for a collection
we should correctly encode it as a collection with 0 elements not
as a null value.
Fixes #518
=> marshal: handle nil collection correctly in udts

marshal.go, marshal_test.go
When marshalling nil values for types which are nullable in
Cassandra we should return a nil slice which will be encoded
as -1 length on the wire which Cassandra will interpret as null.
Fixes #523
=> marshal: correctly marshal nil values

marshal.go, marshal_test.go
gocql panics when I marshal a custom type that aliases for int like this ` type EnumFoo int`.
```
2015/11/09 19:50:03 http: panic serving 127.0.0.1:38775: reflect: call of reflect.Value.IsNil on int Value
goroutine 35 [running]:
net/http.(*conn).serve.func1(0xc8200fc580, 0x7f90518dc898, 0xc820124128)
/usr/local/go/src/net/http/server.go:1287 +0xb5
reflect.Value.IsNil(0x7e7420, 0xc82011c430, 0x42, 0xc82011c430)
/usr/local/go/src/reflect/value.go:971 +0xe3
github.com/gocql/gocql.marshalInt(0x7f90518eab18, 0xc821574960, 0x7e7420, 0xc82011c430, 0x0, 0x0, 0x0, 0x0, 0x0)
(...)/go/src/github.com/gocql/gocql/marshal.go:301 +0x5f9
github.com/gocql/gocql.Marshal(0x7f90518eab18, 0xc821574960, 0x7e7420, 0xc82011c430, 0x0, 0x0, 0x0, 0x0, 0x0)
(...)/go/src/github.com/gocql/gocql/marshal.go:70 +0x9b0 …
```
=> marshal: handle alias type of int correctly.

policies.go, policies_test.go
A nil struct is not the same as an untyped nil interface,
ensure that returned HostInfo is not nil.
Fixes #526
=> policies: ensure NextHost is nil

cassandra_test.go
Listening on all interfaces will trigger the OSX firewall popup.
=> dont listen on all interfaces in tests

conn.go, internal/streams/streams.go, internal/streams/streams_test.go
Replace the bounched chan uniq with a stream ID generator based
very closely on the StreamIDGenerator in the java-driver.
Updates #446
=> conn: replace streams chan with an ID generator

policies.go, policies_test.go
RoundRobbin connection pool should check the available streams on a connection to avoid using busy connections
=> RoundrobbinConnPool check streams

AUTHORS, control.go
Ensure that the atomic variable is aligned to a 64bit boundary so that atomic operations can be applied on 32bit architectures.
Fixes #542
=> control: align atomic variable to 64bit boundary

AUTHORS, session.go
and new page is available.
It enables counting how many pages we gone through calling `Next`.
It is useful in case if you want to stop iteration if you've gone through too many pages, so this method tells when calling `Next` will cause new page fetching.
=> Added a method which returns true if iterator reached end of the page

AUTHORS, helpers.go, marshal.go
I got the `panic: can not marshal string into unknown_type_10` error when use for scylladb, this pull request will fix it
=> add 'text' type support for cylladb

cassandra_test.go, helpers.go, marshal.go, session.go, tuple_test.go
Tuples are handled specially in Scan and as such each element in the
tuple must be treated as a single column. MapScan now generates one
element in the map for each element in the tuple, these can be accessed
by name using the new TupleColumnName function.
fixes #561
=> correctly handle tuples in MapScan

marshal.go, marshal_test.go
As the underlying framer buf is reused between requests the marshaller
must copy the bytes to prevent data corruption.
fixes #567
=> marshal: dont reuse the bytes for inets

host_source.go
When using this driver with the DataStax edition of Cassandra the connect bombs out after the most recent version validation change (was working as of 2 days ago).  This just allows for extra sections in the version string (which should work for DSE and OSS Cassandra).
=> DSE reports >3 elements in the version string

policies.go
I'm guessing this is a typo - we're calling `Unlock`, then defering another `Unlock`, which results in the following panic:
```panic: sync: Unlock of unlocked RWMutex```
=> Fix Unlock of unlocked RWMutex when removing a host from a host policy

AUTHORS, connectionpool.go
Currently, if a new cluster should be created all pools and connections are created in sequence which can take a few seconds in a big cluster. This PR implements concurrent pool creation which speedup cluster initialization.
=> Concurrent connect to hosts

host_source.go, host_source_test.go
Handle more casses of cassandra versions, be more lenient if we dont get
them all.
fixes #579
=> Improve cassandra version parsing

session.go
This PR fixes the incorrect `SelectedHost.Mark()` behaviour if a failed query occurs. Currently, all errors are mistagged as `nil`.
=> mark the selected host with the real query response

cluster.go, events.go, session.go
Add IgnorePeerAddr to cluster config which when enabled will use the
supplied host address instead of the one which the driver discovers from
cassandra.
updates #575
=> Add option to ignore cassandras reported address

session.go
There is the same issue with batch operation. Didn't see it in the previous PR. Would be good to create a follow up ticket to merge some logic into one function because executeQuery/executeBatch looks almost the same.
=> mark the selected host with the real batch response

cassandra_test.go, conn.go, session.go
To be consistent with queries batches should return an error inside and
iter instead of directly. To access to the error callers should use
iter.Close().
Updates #589
=> batch: return an iter containing an error like queries

events_ccm_test.go
only supply one host to the control down event test so that it is a
deterministic host which goes down.
=> for the control down test only supply one host

marshal.go, udt_test.go
If a UDT is updated then it type description will include all fields but
the data will not include all of them.
fixes #595
=> marshal: handle UDTs which are not complete

control.go, events_ccm_test.go, session.go
When the control connection attempts to reconnect and there are no hosts
in the connection pool, fallback to trying the initial endpoints
shuffled again.
Set the host to up after the control connection connects to it.
Simplify control connection reconnecting logic, it is threadsafe as the
only method calling the connect methods is the heartbeater and the
inital connection attempt.
fixes #609
=> control: handle no hosts in connection pool

conn.go, frame.go, session.go
Delay reading the column bytes until scanning so we dont allocate a
large number of byte slices upfront, this has the effect of reducing GC
pressure, which under testing makes reads around 20% faster.
=> Dont read row bytes from framer until scan

session.go
When the connConfig errors the connection pool will not be created,
check that it is not nil before closing it.
=> session: connection pool may be nil on close

AUTHORS, marshal.go, marshal_test.go
Decode `varint` to `uint64` variable in case when it greater then `MaxInt64` and less then `MaxUint64`
=> big uint64 unmarshalling fix

conn.go, session.go
NoSkipMetadata will disable reusing the preapred result metadata when
parsing the query. To work around a bug in Cassandra.
Updates #612
=> query: add NoSkipMetadata option

policies.go, policies_test.go
This was due to that the fallbackHost could be nil but was still accessed to check if the host was the same as the filtered. The behaviour is now similar to the round robin version.
Should fix #544.
=> Fix a panic that could happen when using the TokenAwareHostPolicy

cassandra_test.go, control.go
The token aware host policy needs to fetch schema metadata so it can
hash row keys properly. Before the internal "control" conn was added,
metadata.go would set Query().RoutingKey([]byte{}) before it performed
the metadata queries so the metadata queries themselves didn't re-enter
the token aware host selection code (and deadlock). The control conn
still works most of the time, though, because the control conn performs
queries directly on a conn object, bypassing the token aware selection
stuff. That is, unless there is more than one page of metadata, since
iter.next.fetch() executes the query via the session, which re-enters
the token aware host selection code.
Fix by setting RoutingKey to []byte{} on the control conn's
queries. This is the same tactic the old code was using to avoid …
=> Fix token aware metadata fetching deadlock.

cassandra_test.go, conn.go, host_source.go
It's possible (or at least was possible), to be left with invalid
system.peers entries in your db after changing your
ring (https://issues.apache.org/jira/browse/CASSANDRA-6053 is at least
one way it used to be able to happen). If this happens (or someone who
is already in this state upgrades gocql and is trying to doing peer
discovery), ideally gocql would continue working on the good peers
instead of crashing trying to parse the bad peers. I made two changes
with this goal in mind:
1. Fix version string parsing to not crash if version is too short.
2. Skip peers if we fail parsing the version string (but still return
the peers we were able to parse).
3. When waiting for schema agreement, skip peers that have an empty
schema_version (otherwise it times out and fails).
Our ring had peer …
=> Don't crash on bad peers.

conn.go, conn_test.go
If we get an error when writing a frame, ensure that the select in
closeWithError is not blocked indefinatly, do this by closing the calls
timeout channel before we call closeWithError.
updates #664
=> conn: close call timeout on write error

helpers.go, metadata.go, session.go
This PR is a *very* quick fix to get cluster metadata and TokenAwareRouting working for Cassandra 3.0 clusters. It needs tests, and the code isn't very clean (a lot of names were removed/moved, and I opted to just co-opt the old names from Cassandra 2).
The cluster detection just tests for a single Cassandra 3 node, as the new `system_schema` keyspace depends on Cassandra version, as opposed to the protocol version.
=> Add support for Cassandra 3 system_schema metadata

AUTHORS, conn.go
if a successful response is recieve at the same time as the 10th
timeout, a deadlock can occur if succesfull response is read
from the response channel before closeWithError send an error
of response channel. By closing the call.timeout after reading
from the response channel we can avoid this deadlock.
fixes #664
=> close call.timeout to prevent deadlock.

cassandra_test.go, connectionpool.go
hostConnPool.fill() was synchronously filling the pool and calling
fillingStopped(), which sleeps for ~100ms.
- don't synchronously fill the entire conn pool (connect once
synchronously, then fill the rest in a separate goroutine)
- only sleep in hostConnPool.fillingStopped if fill() encountered an
error
- fix cleanup of bad system.peer in TestInvalidPeerEntry
=> Fix 100ms sleep when creating session.

frame.go, marshal.go, udt_test.go
Fix reflect usage to correct marshal/unmarshal nil collections which are
embedded inside a udt column.
fixes #673
=> marshal: fix udt nil collection marshalling

.gitignore, AUTHORS, cassandra_test.go, marshal.go, marshal_test.go
Got panic while fetching null value for varint type:
```
panic: runtime error: index out of range [recovered]
panic: runtime error: index out of range
github.com/gocql/gocql.unmarshalVarint(0x13b4630, 0xc820075860, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/Users/vecmezoni/go/src/github.com/gocql/gocql/marshal.go:435 +0x40c
github.com/gocql/gocql.Unmarshal(0x13b4630, 0xc820075860, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/Users/vecmezoni/go/src/github.com/gocql/gocql/marshal.go:127 +0x7ae
```
=> Correctly handle null value for varint type

cassandra_test.go, cluster.go, conn_test.go, connectionpool.go, control.go, events.go, host_source.go, policies.go, policies_test.go, query_executor.go, ring.go, session.go, session_test.go
Simplify how queries and batches are executed by making them both
implement the same interface which allows the queryExecutor to handle
both cases.
Remove conn selection policy and let the connection pool make decisions
about which conn to use.
=> add queryExecutor which executes queries.

events.go
Currently the IgnorePeerAddr config option does not work, which causes starting up a session to take a long time since the hosts need to be changed and host pools need to be filled again. I'm sure there's a better solution to handling the host lookup and peer addresses, but for now this pull request fixes the issue.
=> Fixed IgnorePeerAddr config option

conn.go, frame.go, session.go
This function is an addition to `DefaultTimestamp` function.
Using this function enables defaultTimestamp flag, but instead of
generating new timestamp, it is possible to set it's value explicitly.
It's equal to `USING TIMESTAMP x` in the statement, but does not break
prepared query optimization.
=> Implemented WithTimestamp function in gocql.Query

internal/streams/streams.go
- Previously if GetStream() found an available stream but the CAS
failed, it was skipping that stream and trying the next. However, a
CAS failure doesn't mean the current bit is taken, just that some bit
in the bucket changed. Fix to keep retrying the CAS while the bit it's
checking continues to be available in the bucket.
- When the CAS failed in GetStream(), it was re-loading the bucket using
"offset" instead of "pos". This wouldn't end up causing any incorrect
behavior, but it greatly reduces the chance of finding an available
bit in the current bucket since the CAS will only succeed if
c.streams[pos] happens to be the same as c.streams[offset] (assuming
pos != offset).
=> Fix two bugs in stream id allocation.

cassandra_test.go, conn.go, conn_test.go, control.go, session.go
Add WithContext on Batch and Query to supply a context which will cause
queries to abort when the context is cancelled/timeouted or done.
fixes #676
=> query: add context support

cassandra_test.go, conn.go, control.go, frame.go, frame_test.go
The connection startup loop did not return the correct error when failing to connect to a host with an unsupported version, and the control connection would hide the error returned from dial and not return this to the session, leading to incorrect errors being returned from createSession.
fixes #716 
updates #713
=> session: dont swallow createSession errors

conn.go, frame.go
If we are in protocol 2 mode we will allocate an 8 byte header buffer,
if the server does not support protocol 2 it will respond with a 9
byte header. Always allocate a 9 byte header but only use 8 if we are
in protocol 2 mode.
fixes #721
=> conn: always allocate 9 bytes for the header buf

cassandra_test.go, cluster.go, conn.go, events.go, events_ccm_test.go, session.go
Hi, guys.
I've found that gocql doesn't try to reconnect to nodes which connection has been closed with TooManyTimeouts error.
For now, once a node goes DOWN, gocql can't get it back to UP status without UP server-push events.
But in some cases, gocql make nodes DOWN by itself. (e.g. after timeouts : https://github.com/gocql/gocql/blob/51009831ae7a79fd8f1b160d7359916a7a044afa/connectionpool.go#L399 )
In those case, UP events will not occur naturally so the node can't get back to UP forever.
So, I think polling for the DOWN nodes to make them UP would be a good way to keep connections.
Thanks.
=> Attempt to reconnect known DOWN nodes

AUTHORS, host_source.go
Adds a call to SetPartitioner on the session's HostSelectionPolicy. 
This is mostly needed so that the token aware policy initializes 
and updates its token ring representation.
Fixes #724 
- I've updated my email address in the AUTHORS file.
=> Notify the HostSelectionPolicy of the partioner

conn.go
Hi, again!
In my environment, many ErrTooManyTimeouts occurs and many in-flight requests are closed with the error abruptly.
I'm not sure if counting timeouts would be a good way to detect failure for the coordinator nodes.
Timeouts can be occurred by not only coordinator nodes but also specific heavy query( like scanning ) or heavy-loading of data-nodes.
Also, I'm thinking of HostSelectionPolicy might be a good place to handle these kind things.
So, In this branch, I'd like to add an option to avoid this way to ErrTooManyTimeouts by setting TimeoutLimit zero.
I'd appreciate it if you could review this PR.
Thanks.
=> Avoid ErrTooManyTimeouts if TimeoutLimit is 0

helpers.go, marshal.go, marshal_test.go
Handle cql small int and tiny int, these are 16 bit and 8 bit signed
ints.
Fix unmarshalling uints to correctly set the max value of the int when
the sign bit is extended to a larger type. This fixes it so that it
correctly unmarshalls a tiny int of value 0xFF into any uint 0xFF
instead of the max value of the unit type.
fixes #733
=> marshall: support small and tiny ints, fix uint

AUTHORS, session.go, session_test.go
Queries account for a lot of unnecessary allocations. This PR exposes a `Release` method on the `Query` type so that callers of `Session.Query()` can reduce the number of allocations.
=> Pool query objects

cluster.go, conn.go
Hi.
After we `ALTER TABLE ADD COLUMEN...` on a live cluster, almost all C* clients using gocql failed with panic.
As a result of some investigation, we found that the panic has been caused by [CASSANDRA-10786](https://issues.apache.org/jira/browse/CASSANDRA-10786).
The metadata for EXECUTE ROWS results have been changed after a `ALTER TABLE` but only one client can handle the change of the metadata. Other clients failed to unmarshal (especially for parse of collection type) and panic.
So, In this ticket, I'd like to add a way to disable SkipMetadata within the session to avoid this issue.
=> Add Session.DisableSkipMetadata to avoid panic by CASSANDRA-10786

frame.go, session.go
This function is an addition to DefaultTimestamp function.
Using this function enables defaultTimestamp flag, but instead of
generating new timestamp, it is possible to set it's value explicitly.
It's equal to USING TIMESTAMP x in the statement, but does not break
prepared query optimization.
Similar to #706 PR but for batches.
=> Implemented WithTimestamp function in gocql.Batch

AUTHORS, connectionpool.go
Minor change to the connection pool code that uses the *net.OpError type
to pull of retrying to connect to a host if the error is a permanent
erorr.
Reduces startup time on creating a new sesession when we try to
establish a connection using gocql that does not have visibility to the
host.
Performance improvement easily reproduced when using default cassandra
docker container with gocql.
Relates to issue #696
=> Stop retrying to connect on permanent failure

AUTHORS, cassandra_test.go, helpers.go
Problem:
When using `SliceMap` with a schema containing a `smallint`, gocql panics
```
events | 2016/07/13 23:58:25 http: panic serving 192.168.99.1:56947: reflect: New(nil)
events | goroutine 43 [running]:
events | net/http.(*conn).serve.func1(0xc8202b5880)
events | 	/usr/local/go/src/net/http/server.go:1389 +0xc1
events | panic(0x857e40, 0xc8202b6e80)
events | 	/usr/local/go/src/runtime/panic.go:443 +0x4e9
events | reflect.New(0x0, 0x0, 0x0, 0x0, 0x0)
events | 	/usr/local/go/src/reflect/value.go:2119 +0x85
events | github.com/buoyantio/helium/vendor/github.com/gocql/gocql.NativeType.New(0x7f9d00000003, 0x13, 0xc820145680, 0x29, 0x0, 0x0)
events | 	/go/src/github.com/buoyantio/helium/vendor/github.com/gocql/gocql/marshal.go:1788 +0xd6
events | …
```
=> Add reflection support for smallint

AUTHORS, marshal.go, udt_test.go
The CQL binary protocol specification states that a serialized UDT is
allowed to have _less_ values than it has fields:
> A UDT value will generally have one value for each field of the type it represents, but it is allowed to have less values than the type has fields.
This is also evident in the Cassandra Java driver's UDTCodec class:
```java
public UDTValue deserialize(ByteBuffer bytes) {
ByteBuffer input = bytes.duplicate();
UDTValue value = definition.newValue();
int i = 0;
while (input.hasRemaining() && i < value.values.length) {
int n = input.getInt();
value.values[i++] = n < 0 ? null : readBytes(input, n);
}
return value;
}
```
Fix the unmarshalUDT() function to check whether there's more data to
read to avoid accessing a slice out of bounds:
```
panic: runtime error: slice bounds …
```
=> marshal: Fix unmarshalUDT for less values than UDT fields

README.md
ScyllaDB is a fast Apache Cassandra compatible NoSQL database that is
used with gocql in production for high performance deployments:
http://developer.eniro.com/blog/post/scylladb-a-monster-or-a-rock/
Add ScyllaDB to the "Ecosphere" section of gocql's README so that people
know gocql also integrates very well with ScyllaDB.
=> Add ScyllaDB to "Ecosphere"

frame.go, frame_test.go
This PR adds the suggested ParseConsistencyWrapper including a simple test for it.
[Fixes #749]
=> Non-panic ParseConsistency added (#749)

AUTHORS, host_source.go, session.go
When `DisableInitialHostLookup` is true, `addrToHost` is called instead of doing a lookup in `system.local` and `system.peers`. This means that the host's version is the zero value (version 0) for all hosts.
Thus, calls to `KeyspaceMetadata` fail for cassandra versions >= 3.x because gocql attempts to make queries on `system.schema_keyspaces`, which no longer exists.
This PR simply stipulates that if `DisableInitialHostLookup` is true, we should use CQL version specified by the ClusterConfig that was used to create the session. Otherwise, we use the version of the first host, as before.
=> Use correct CQL version even if `DisableInitialHostLookup` is true

cluster.go, events.go, session.go
DiscoveryConfig was replaced with the HostFilter, DiscoveryConfig was
not fully ported over when adding host events.
=> config: remove legacy DiscoveryConfig

README.md
and HTTPS links where possible
NOTE: the project url at the top of the page on GitHub could also be using HTTPS.
> Package gocql implements a fast and robust Cassandra client for the Go programming language. http://gocql.github.io/
=> readme: svg badge for “retina” displays

cassandra_test.go, cluster.go, conn.go, conn_test.go, connectionpool.go, control.go, control_test.go, events.go, events_ccm_test.go, filters.go, filters_test.go, host_source.go, policies.go, policies_test.go, query_executor.go, ring.go, ring_test.go, session.go, token.go, token_test.go
When Cassandra returns a hosts info the peer address is defined as an
inet both at protocol for events and the schema for the peer
information.
Previously this was stored as a string, and is used to
connect to hosts and also to index hosts by. This is different to what
happens for a user supplied address, the potentially DNS name is kept 
as the peer address. This means that there can be duplicate
host pools, duplicate host info in the ring.
Fix this by making everything rely on a hosts address being an IP
address instead of either a DNS name or an IP.
=> change HostInfo.Peer to be an IP

prepared_cache.go, prepared_cache_test.go
This change introduces the usage of an RWMutex in order to use `RLock` in the execIfMissing.
Benchmark results using the the old way:
```
BenchmarkLRU                    10000000               185 ns/op               0 B/op          0 allocs/op
BenchmarkLRU-2                  10000000               178 ns/op               0 B/op          0 allocs/op
BenchmarkLRU-4                   5000000               212 ns/op               0 B/op          0 allocs/op
BenchmarkLRU-8                   5000000               248 ns/op               0 B/op          0 allocs/op
BenchmarkLRU-16                 10000000               222 ns/op               0 B/op          0 allocs/op
BenchmarkLRU-24                  5000000               240 ns/op               0 B/op          0 allocs/op
BenchmarkLRU-32 …
```
=> Use RWMutex in prepared statement cache

AUTHORS, metadata.go
In response to issue #820 this patch adds ColumnStatic to the ColumKind enum
I have not added any new test for the extra iota value. I'm happy to if you can point me in the right direction for those. I was having some trouble running tests locally - 
```
package ghe.iparadigms.com/ndavies/gocql
imports github.com/gocql/gocql/internal/lru: use of internal package not allowed
package ghe.iparadigms.com/ndavies/gocql
imports github.com/gocql/gocql/internal/murmur: use of internal package not allowed
package ghe.iparadigms.com/ndavies/gocql
imports github.com/gocql/gocql/internal/streams: use of internal package not allowed
```
The patch itself is fairly straightforward and I think I've got it in the right spot. Thanks
=> Add support for STATIC

address_translators.go, address_translators_test.go, cluster.go, cluster_test.go, common_test.go, conn.go, conn_test.go, control.go, events.go, integration.sh, session_connect_test.go, session_test.go, udt_test.go
This change introduces the AddressTranslator interface, which is
intended for use during discovery and node-event processing to translate
peer addresses of nodes. The primary use -- which is driving the
change -- is to translate public IPs to private IPs (when possible)
in ec2. The ec2 translator will be implemented elsewhere and is not
provided here.
This solution is common among other CQL driver implementations. The
specific implementation here also follows the convention set by
HostFilter.
We try our best to have test coverage for the bits that changed.
Signed-off-by: Justin "Gus" Knowlden gus@gusg.us
=> adding AddressTranslator interface and impl for use in ec2

frame.go, session.go
Took a shot at implementing #813.
I store the warnings inside the header, mostly because the custom payload is there already so it made sense.
=> add the Warnings function on Iter

session.go
If you call `Warnings()` on an iterator without a framer, it panics today. It happened to me on an iterator with an error.
This fix checks the framer is not nil.
=> check that the framer exists before trying to access the warnings

marshal.go
When inserting a UDT via a map, allow the map to be a subset of the UDT.
Fixes #841
=> marshalUDT: allow not using all the UDT fields

control.go
```console
==================
WARNING: DATA RACE
Read at 0x00c42023c000 by goroutine 87:
math/rand.(*rngSource).Int63()
/usr/local/go/src/math/rand/rng.go:231 +0x3f
math/rand.(*Rand).Int63()
/usr/local/go/src/math/rand/rand.go:81 +0x51
math/rand.(*Rand).Int31()
/usr/local/go/src/math/rand/rand.go:95 +0x38
math/rand.(*Rand).Int31n()
/usr/local/go/src/math/rand/rand.go:127 +0xd2
math/rand.(*Rand).Intn()
/usr/local/go/src/math/rand/rand.go:144 +0x52
math/rand.(*Rand).Perm()
/usr/local/go/src/math/rand/rand.go:197 +0xa2
github.com/.../github.com/gocql/gocql.(*controlConn).shuffleDial()
/.../vendor/github.com/gocql/gocql/control.go:109 +0x6f
```
=> control.go: fix race condition on randr

conn.go
A timer will only be garbage collected once it has fired, if a call
returns before the timeout is reached then it will not be garbage
collected, leading to potentially many timers on the heap.
fixes #851
=> conn: fix memory leak when using long timeouts

AUTHORS, cassandra_test.go, metadata.go, session.go
Previously if a keyspace did not exist a partially empty `KeyspaceMetadata` struct was returned. From what I could see, the more appropriate behaviour would be to return an error indicating so.
Detecting if the keyspace actual exists is done by checking the number of rows returned from the query to the system table `system_schema.keyspaces`. If there were no rows returned then that indicates the keyspace doesn't exist.
No unit tests exist for the called function (`geKeyspaceMetadata`) though an integration test exists for `KeyspaceMetadata()`. A subsequent integration test was added which attempts to get the metadata for a keyspace that is known to not exist.
A slight update to the godoc for KeyspaceMetadata() was added detailing this new behaviour.
Solves issue #849.
=> Change KeypsaceMetadata() to return an error if the keyspace does not exist 

AUTHORS, cluster.go, conn.go, conn_test.go, connectionpool.go, logger.go
In large clusters with busy nodes it is not uncommon to have a high connection timeout to tolerate large or longer running queries. With such a configuration and with nodes under heavy load `CreateSession()` can block for the duration of the high timeout `x3` for each node not responding in a timely manner. This can cause issues (See #839) where either a temporary network issue causes connection issues or the connection was successful but Cassandra doesn't respond with the startup frame in a timely manner.
* Introduced a new timeout `ClusterConfig.ConnectTimeout` which is only applied during the initial dial and exchange of startup frames.
* Added a test called `TestStartupTimeout` to ensure timeout while waiting for startup frame works and is separate from `ClusterConfig.Timeout`
=> Separate ConnectTimeout from Timeout

README.md
It has more up-to-date support for Cassandra.
/cc @gravis @mattes
ref: https://github.com/mattes/migrate/issues/127
ref: https://github.com/gemnasium/migrate/blob/master/CHANGELOG.md
=> suggest journey, Gemnasium's fork of the migrate library

session.go
I started using contexts in my code which uses gocql and noticed a lot of my unit tests failed recently with errors like `gocql: unable to create session: context canceled` and sometimes it logged lines like `gocql: events: unable to fetch host info for (127.0.0.1:9042): context canceled`.
My code does something like this:
```go
ctx, cancelFn := context.WithTimeout(context.Background(), 10*time.Second)
defer cancelFn()
qry := session.Query(q, apiKey.Key, apiKey.Platform).WithContext(ctx).Consistency(cons)
defer qry.Release()
session.Close()
``` 
in each test. With `reset()` not clearing the context, the next test has a chance to fail because the context has been canceled, but it's still there in the query I just released. It happens almost everytime in my unit tests.
=> reset the context when calling Query.reset

cassandra_test.go, common_test.go, conn.go, connectionpool.go, control.go, control_test.go, events.go, filters.go, filters_test.go, host_source.go, host_source_test.go, policies.go, policies_test.go, ring.go, ring_test.go, session.go, session_connect_test.go, token.go, token_test.go
In order to preform more complex host filtering for large clusters, more information on cluster peers is required. This implementation follows the Java Driver method of collecting local and peer host information, which makes the collection of cluster node information more version tolerant. `system.local` and `system.peer` fields that are available for newer clusters versions are safely omitted when running against older clusters.
* Introduced `HostInfo.ConnectAddress()` as a consistent way of retrieving the desired node address. The previous use of `Peer()` as the connect address was overloaded with the `peer` field in the `system.peers` table. In addition it would appear the code was connecting via the `Peer()` address, unless you where aware the code explicitly overwrote `Peer()` with …
=> GetHosts() is now more version tolerant

batch_test.go, conn.go
Wasn't passing along defaultColumnTimestampValue when creating the
batch frame.
=> Fix setting batch timestamp.

marshal.go
In order to test an implementation of `gocql.Unmarshaler` or `gocql.Marshaler` I need to pass it a `gocql.TypeInfo`.
Until today I just did that indirectly by creating tables and querying cassandra directly, but it's taking  a long time to spin up a Cassandra for my CI builds.
So I looked at a way to build the `gocql.TypeInfo` myself, and turns out the interface is not that complicated so I made my own type for it.
But, it's kind of a waste because I ended up duplicating [this](https://github.com/gocql/gocql/blob/6a9363e0c9b27431ce2ed5872279f85248115b9e/helpers.go#L22), and my TypeInfo was basically just [this](https://github.com/gocql/gocql/blob/master/marshal.go#L1796) copied. 
`NativeType` is the only type with fields not exposed so I can't use it directly, which is why I'm suggesting …
=> add the constructor NewNativeType

cassandra_test.go, control.go
It was getting stuck when the trace queries via control connection
re-entered the trace code (since they use the same session). Fix by
unsetting Trace on the control connection queries so it doesn't try to
trace the traces.
=> Fix session level tracer.

cassandra_test.go, metadata.go
Decided to run `go test -tags all` with a Cassandra 2.2.9 running tonight. A failing test caught my attention:
G:\Gopath\src\github.com\gocql\gocql [fix-table-metadata]> go test -v -tags "all" -run="TestGetTableMetadata"
=== RUN   TestGetTableMetadata
2017/03/16 00:54:27 common_test.go:121: closing keyspace session
--- FAIL: TestGetTableMetadata (4.41s)
cassandra_test.go:1705: failed to query the table metadata with err: Error querying table schema: Undefined name key_aliases in selection clause
FAIL
exit status 1
FAIL    github.com/gocql/gocql  4.590s
This simple program exhibits the problem too:
```go
package main
import (
"log"
)
func main() {
cfg := gocql.NewCluster("127.0.0.1:9042")
cfg.ProtoVersion = 2
session, err := cfg.CreateSession()
if err != nil { …
```
=> metadata: key_aliases are only relevant with proto version 1

conn.go
closeWithError will hold the lock and close the channel, which we could
be assigning at the same time.
fixes #852
=> conn: hold mutex while creating calls

host_source.go
While ring refreshing if we have found hosts not added to ring yet, we need add them not only to connection pool but into policy poll too.
=> Add hosts to policy pool on ring refreshring

AUTHORS, marshal.go, marshal_test.go
What
===
Add a descriptive error when a UUID is marshaled or unmarshaled and the length of the `[]byte` is not exactly 16 bytes long.
Example
===
```
can not marshal []byte 6 bytes long into timeuuid, must be exactly 16 bytes long
```
Why
===
In cases where UUID `[]byte` was not the correct length the generic `can not marshal %T into %s` error was being returned. The error was misleading because it gave the impression the root cause was the type of the data and not it's length. Additionally the `%T` formatter for a `[]byte` prints out `[]uint8` which was even more confusing.
Notes
===
This PR contains three commits. It's easier to digest the change if you review them separately as the first refactors the tests to support expectations on the error itself.
Ref
===
Fixes #868
=> marshal: Add an error when UUID has wrong length

conn_test.go, session.go
`CreateSession()` would exit prematurely if it encountered a hostname it could not resolve. With this patch all host names will be resolved before an error is returned. fixes #873 
* `addrsToHosts()` will log and continue to the next host if `hostInfo()` returns a `DNSError`
* Added an error if none of the host names can be resolved
=> CreateSession() will now attempt to resolve all host names

conn.go, connectionpool.go
This embeds a pointer to the desired TLS config instead of a concrete value. Because Go copies the arguments of all function calls, this has the side effect of copying the TLS configuration, which copies a mutex. This causes `go vet` to report that `crypto/tls.Config contains sync.Once contains sync.Mutex`.
This patch removes this complaint, but at the cost of needing people to change their Cassandra TLS configuration code to remove the dereference of the TLS config when assigning to the `Config` field of the TLS configuration.
EG:
```go
func createTLSConfig(caCertConfigValue string) *gocql.SslOptions {
caCertPool := x509.NewCertPool()
caCertPool.AppendCertsFromPEM([]byte(caCertConfigValue))
config := &tls.Config{
RootCAs: caCertPool,
}
config.BuildNameToCertificate()
return …
```
=> SslOptions: embed a pointer to the TLS config

conn.go
Currently gocql will cache the timeout err caused by network instability when prepare a statement.
As a result, if gocql fails to prepare a statement due to network issue at the first time on a connection, the rest of the call to that statement on that connection would return "context deadline exceeded”. 
It can result in high and consistent err rate and can only fixed by restart a host.
We have been suffering from this in production for a while.
=> fix consistent high timeout err rate caused by prepareStatement

conn.go
This is a correction for #892 
If we remove flight.err = err
This [code](https://github.com/gocql/gocql/blob/master/conn.go#L703-L706) may accidentally return no err, when it should return one.
=> flight.err should still be set even if flight is removed from cache

.travis.yml
What
===
Add go1.8 and remove go1.6 from CI tests.
Why
===
It's the latest Go release and we should be ensuring tests pass on it and according to the gocql README the last two major versions will be supported. The last two major versions are go1.7 and go1.8.
=> Add go1.8 to CI tests

cassandra_test.go, conn.go, conn_test.go, control.go, session.go, session_connect_test.go
Remove an external dependency since it's been incorporated into the stdlib.
=> Replace golang.org/x/net/context with stdlib context

cassandra_test.go, conn.go, frame.go, marshal.go
Adding support for the UNSET_VALUE in gocql.  See #861 and [Cassandra Jira issue](https://issues.apache.org/jira/browse/CASSANDRA-7304)
=> Support for UnSet columns

conn.go
To address #902
Make executeBatch behaves the same as executeQuery when C* returns RequestErrUnprepared
=> executeBatch return proper err for RequestErrUnprepared

AUTHORS, policies.go, policies_test.go
To improve reliability in the event of a flaky network, we want to use this retry policy, which has a configurable backoff and uses some jitter to mitigate thundering herds when the network is misbehaving.
=> Add exponential backoff retry policy

AUTHORS, cassandra_test.go, query_executor.go
The function below always return `nil` because the value it queries is never set.
```
// session.go
// Host returns the host which the query was sent to.
1050: func (iter *Iter) Host() *HostInfo {
1051:	return iter.host
1052:}
```
This is because the host is never set in the Iter structure.
Add the host to Iter when the query is executed with success on a host (query_executor.go:50)
Add a test to check if the host is well set on a successful query
=> Fix iter Host method

cassandra_test.go, common_test.go, conn.go, connectionpool.go, control.go, control_test.go, events.go, filters.go, filters_test.go, host_source.go, host_source_test.go, policies.go, policies_test.go, ring.go, ring_test.go, session.go, session_connect_test.go, token.go, token_test.go
This is the fixed version of PR #860 (See #869)
During  initial discovery gocql will only use the user supplied address when picking a control host.
Peers that are discovered will have an `rpc_address` or `peer` address which will be used to connect. 
```go
// session.go
186:	for _, host := range hosts {
187:		host = s.ring.addOrUpdate(host)
188:		s.handleNodeUp(host.ConnectAddress(), host.Port(), false)
189:	}
```
Also
```go
// host_source.go
151: func (h *HostInfo) ConnectAddress() net.IP {
152: 	h.mu.RLock()
153: 	defer h.mu.RUnlock()
154: 
155: 	if h.connectAddress == nil {
156: 		// Use 'rpc_address' if provided and it's not 0.0.0.0
157: 		if h.rpcAddress != nil && !h.rpcAddress.IsUnspecified() {
158: 			return h.rpcAddress
159: 		}
160: 		// Peer should always be set if this from …
```
=> Fix more hostinfo

host_source.go, host_source_test.go
If the rpc_address is set to 0.0.0.0 then we should use
broadcast_address if it is set.
=> host: use broadcast_address in ConnectAddress

filters.go
=> WhiteListHostFilter: use IP.String() for the filter key

host_source.go, ring.go
The system.local table might not have the address info for the connected
host, if this is the case use the connect address from the control
connection.
Add more checks that the connect address is valid to not end up adding
invalid hosts.
=> host_source: correctly get local hostinfo

AUTHORS, conn.go
When 'nodetool settraceprobability' is used,
it's possible to get a response frame with trace information
even though client did not specifically mark the query
for tracing.
There are two places in conn.go where this can cause SIGSEGV, prepareStatement and executeQuery. 
The prepareStatement path was fixed in https://github.com/gocql/gocql/commit/990865929b372dba9393b0ba8e4967288594b59b
=> avoid SIGSEGV by not tracing unless query is trace enabled

policies.go, policies_test.go
Add a simple host policy to select local dc hosts before remote hosts.
Fixes #913
=> policies: add simple DCAwareRoundRobin policy

AUTHORS, policies.go, policies_test.go
Spelling nit so DCAwareRoundRobinPolicy lines up with regular RoundRobinHostPolicy.
Update AUTHORS.md
=> Fix spelling for DCAwareRoundRobinPolicy

host_source.go, ring.go, session.go
When refreshing the ring remove hosts from the drivers ring cache to
prevent it from trying to connect to removed hosts if it does not
receive a down host event.
=> hostsource: remove hosts no longer in peers

marshal.go, marshal_test.go
When we read null from the wire it is encoded as -1 which gets returned
from the frame as []byte(nil), this is distinct from the framer reading
a length 0 byte which is returned as []byte{}, these both have 0 length
but one is nil the other is empty.
Fix marshalling to correctly handle nil and empty values.
fixes #954
=> marshal: fix is nullable check

AUTHORS, policies.go
This PR makes sure that the sleep time for ExponentialBackoffRetryPolicy never exceeds Max.
Max was already defined in the struct but not used.
=> Respect exponential retry Max

.travis.yml
Latest stable version is Go 1.9, so I propose to officially support it.
=> Add Go 1.9 to CI

marshal.go, tuple_test.go
UDT and Tuple values are [byte] which can return nil. UDT handled this
and lots of special handling for the slicing the data. Create readBytes
which correctly reads the bytes and handles nil. Use this in tuple and
UDT. Add testcase for tuples.
=> marshall: correctly handle null tuple elements

AUTHORS, policies.go, policies_test.go
DCAwareRoundRobinPolicy currently picks the first host in a map
of all local and remote hosts. This has a tendency to pick the same
host more frequently than others, resulting in an uneven distribution
of operations within the cluster. Modify DCAwareRoundRobinPolicy to
more closely match the RoundRobinHostPolicy by always incrementing the
hosts in a DC.
=> fix DCAwareRoundRobinPolicy host distribution

AUTHORS, frame.go, frame_test.go
This PR adds text marshaller and unmarshaller for `Consistency` and `SerialConsistency` it removes panic recover behavior while parsing. https://github.com/gocql/gocql/pull/983/commits/ab2b96ae82252983855b8291290d4b12fe8d3c75 changes the parsing method naming to more common ones.
=> Consistency no panic

cassandra_test.go, common_test.go, conn.go, conn_test.go, control.go, events.go, helpers.go, host_source.go, host_source_test.go, query_executor.go, ring.go, session.go, session_connect_test.go
Simplify and refactor host discovery, replace methods for discovering
ring info to use the same methods everywhere. Don't store host info on
the connection instead the control connection knows its own host and all
others are discovered. Don't trigger hostUp from the control connection
isntead use only discovered hosts from session init.
Clean things up around, unexport Connect to be a private API.
updates #987, #946
=> refactor host discovery

control.go
Read the environment variable `GOCQL_HOST_LOOKUP_PREFER_V4` to prefer ipv4 lookup
=> enable ipv4 preferred lookup using an environment variable

AUTHORS, internal/murmur/murmur_test.go
During Debian autobuilds on 32-bit platforms (armhf, i386) we noticed that one of the expected result hash values, when given as a literal number, overflows `int`. This causes the build of the testing code to fail on such platforms. Explicitly requiring the value to be 64-bit fixes this.
=> fix failing murmur tests on 32-bit platforms

host_source.go
Use the correct *HostInfo in the comparison
Fixes #1013
=> ring describer: fix getHostInfo

conn_test.go, control.go, control_test.go, session.go
When using a DNS name as your connection point, this allows the client to attempt to connect to multiple nodes in the cluster when creating the control connection.
We've encountered an issue where our DNS will sometimes return a temporarily offline host first from DNS.  During this time, any client that attempts to bootstrap will return an error as it will only try to connect to that host.  Since we return many hosts in our DNS, the client should attempt to connect to several of them, as if we had passed in a list of IP addresses.
=> Connect to multiple hosts behind a DNS name

uuid.go, uuid_test.go
Hi, guys.
In some reasons, I'm implementing a comparator for version 1 `gocql.UUID` in my project  (Actually, I'm mocking Cassandra). For this implementation and testing, it would be great if gocql has ability to generate `gocql.UUID` with given parameter (timestamp, clock sequence and node id) and accessors those parameters.
These abilities might be unnecessary for a CQL driver. But I think they're convenient for some users. Could you guys review this propose?
Thanks.
=> Add func TimeUUIDWith(t int64, clock uint32, node []byte) UUID 

AUTHORS, session.go
When trying to connect to a cluster some users of this package receive
"no connections were made when creating the session"
This issue was introduced in commit  [Remove HostFilter for supplied hosts (#1012)](https://github.com/gocql/gocql/commit/aa93acc8f067e9233982b9a7de370e4d64b9c33e)
because hosts are now completely replaced by the 'list of hosts the cluster knows about' as apposed to being appended to the existing list.
This pull request resolves this issue and resolve issue #1020
=> Fix no connection being made due to host replacement

batch_test.go, cassandra_test.go, common_test.go, conn.go, events.go, frame.go, policies.go, policies_test.go, query_executor.go, session.go, token.go, token_test.go, topology.go, topology_test.go
Add support for finding token replicas based on the placement stategy
for each keyspace.
Update host policies to recieve keyspace change updates and the ability
to set the session once they are created.
=> TokenAwarePolicy: use token replicas per placement strategy

policies.go
Add method for host selection policies to indicate if a node should be
considered local. Currently this is only used when using the DCAwareRR
policy with a TokenAware policy.
=> policies: add IsLocal

helpers.go, helpers_test.go, marshal.go, metadata.go
Parse the correct TypeInfo from the cassandra string in the db. Fixing
representation to recursivly parse the nested types.
=> metadata: fix all types being NativeType

marshal.go
When trying to marshal a value with the wrong type into a int, smallint or tinyint, marshalInt, marshalSmallint and marshalTinyint fail with a panic because IsNil is called on a non-pointer value.
Test program:
package main
import (
"log"
)
func main() {
cfg := gocql.NewCluster("localhost:9042")
session, err := cfg.CreateSession()
if err != nil {
log.Fatal(err)
}
const (
tableDDL = `CREATE TABLE test.foobar (id text PRIMARY KEY, val int, val2 tinyint, val3 smallint)`
)
if err := session.Query(tableDDL).Exec(); err != nil {
log.Printf("unable to create table: %v", err)
}
err = session.Query("UPDATE test.foobar SET val = ? WHERE id = ?", float64(456), "foobar").Exec()
if err != nil {
log.Print(err)
}
err = session.Query("UPDATE test.foobar SET val2 = ? WHERE id = …
=> marshal: fix marshalling of ints with a wrong type

AUTHORS, conn.go
Issue: https://github.com/gocql/gocql/issues/896
Send the frame asynchronously, so a request can timeout properly when network is slow
=> send frame should not block

cassandra_test.go
Fixing expected value for test case.
=> Fixing expected value for TestRebindQueryInfo when q.Bind(24).

AUTHORS, cluster.go, cluster_test.go, connectionpool.go, control.go, policies.go
PR for #1079 
Reconnection policy: 
decides how to reconnect before marking host as 'down'.  Implemented 2 reconnection policies - `ConstantReconnectionPolicy` (default) and `ExponentialReconnectionPolicy`. Refactored the existing policies and gave the exponential retry logic a separate function to be shared by `ExponentialReconnectionPolicy` and `ExponentialBackoffRetryPolicy`.
Opened interface in policies.go for user to implement their own policies.
=> Add reconnection policies

cluster.go, cluster_test.go, connectionpool.go, control.go, policies.go
#1079 
Conviction policy: 
decide when to mark the host as 'down' based on the error. Default:  `SimpleConvictionPolicy` - mark host as 'down' on any error.
Opened interface in policies.go for user to implement their own policies.
=> add conviction policy interface

conn.go
It was done everywhere else, except here.
=> conn: add missing remove prepared statement from cache on error

session.go
So query creation is more efficient as well as as identical as possible in Session.Bind and Session.Query.
=> Improve query pool

conn.go
Don't put the framer into the pool when we may return it on the iter which when closed will return it to the pool.
updates #1103
=> conn: fix potential framer reuse in prepare

go.mod, go.modverify
What
===
Update the vgo files, go.mod and go.modverify using the latest version
of vgo, `vgo:2018-02-20.1`.
Why
===
A recent version of vgo shipped changes to how go.modverify is populated
for packages hosted as gopkg.in, and removed quotes from package names.
Resolves #1130.
cc @dahankzter @myitcv @nightlyone
=> Update vgo go.mod and go.modverify

cluster.go, conn.go, session.go
Much like the `QueryObserver`, the `ConnectObserver` is called when a new connection
is made.
We use this in production every day, exactly like the `QueryObserver`. We can then graph the connections made to our cluster and detect potential problems when we see a lot of new connections made when it should not.
=> conn: add ConnectObserver

query_executor.go, session.go
By passing the Conn, we can now have the address of the cassandra node which
made the query/batch.
This is very useful as we can now graph our latencies per nodes.
=> ObservedQuery,ObservedBatch: pass the address of the node

connectionpool.go
I built this with `-race` and ran it against a cassandra node with SSL enabled.
```go
package main
import (
"fmt"
)
func main() {
cluster := gocql.NewCluster("host")
cluster.Keyspace = "Keyspace"
cluster.ProtoVersion = 4
cluster.SslOpts = &gocql.SslOptions{EnableHostVerification: false}
cluster.Authenticator = &gocql.PasswordAuthenticator{Username: "Username", Password: "Password"}
for i := 0; i < 10; i++ {
session, err := cluster.CreateSession()
if err != nil {
fmt.Println(err)
}
session.Close()
}
}
```
It trips a race.
Every time gocql starts a session it sets InsecureSkipVerify. That value is then read later by TLS in goroutines.
On a subsequent session, InsecureSkipVerify is updated again in the main routine. Now I've mixed a  load and store across routines …
=> return deep copy of ssl config

conn.go
fixes #1146 
I think at the time of adding keep alive feature https://github.com/gocql/gocql/pull/118 there is no field keep alive in the dialer and hence might not be done.
=> Update keepalive in the dialer

session.go
This passes the query's current attempt number to the query observer which is rather helpful for logging and alerting.
=> Add attempt to query observer

AUTHORS, conn.go, conn_test.go, policies.go, query_executor.go, session.go
This adds the ability to constrain the runtime of individual query attempts. Right now we have the situation that there are no retries if the coordinator times out responding as there's only the possibility to time out a query via the context. This is also somewhat related to https://github.com/gocql/gocql/issues/812#issuecomment-257107273.
In working with this we found and fixed a couple of related problems:
1. Contexts expiring or canceled while the query executor was in the retry loop were not respected and always resulted in the `conn.exec` to still write the query to the connection because the context was checked too late.
2. The query executor's attempt loop was simplified to bail earlier.
The test we implemented to check whether retries are done and respect the per-attempt timeout …
=> Provide a way to limit per-query-attempt deadlines

conn_test.go, query_executor.go
If a retry policy is defined for the session/query, retries wouldn't stop even if the retry policy returned false in the call to `Attempt()`. The bug was introduced in #1151. As long as queries keep failing and no other condition applies the query would be retried. One such condition being the exhaustion of the host pool but even that might not happen in the case where the retry policy always returns `Retry` and retries are executed on the same connection. This might lead to any number of unexpected behaviors, even going as far as looping endlessly if the session/query doesn't have a timeout defined and no context is used that would eventually be canceled or time out.
The unit test that checks the retries being executed now checks for an exact number of query retries, making it a …
=> Fix bug in query executor that prevented retries from ceasing

errors.go, frame.go
This error can be [thrown](https://github.com/apache/cassandra/blob/trunk/src/java/org/apache/cassandra/exceptions/ExceptionCode.java#L45])
=> Add CDC error

conn_test.go, control.go, helpers.go
`skipLong` option allows skipping DNS and StartupTimeout tests, making unittests run in under 5s. 
Considering that we run unittests a lot to make sure stuff is not overly broken, this saves a lot of time during dev.
Signed-off-by: Alex Lourie <alex@instaclustr.com>
=> Shorten runtime for long tests

AUTHORS, conn.go, conn_test.go, policies.go, query_executor.go, session.go
This reverts #1151 (and #1164 by association because it builds on top of it) because we introduced a serious issue reported in #1161.
I'll open a new PR with better tests, do a more rigorous review and also use that version in our staging services first (/cc @ekle to keep him in the loop).
=> Revert #1164 and #1151

marshal.go, marshal_test.go
We don't aloways need to allocate a new slice to unmarshal into when the
passed in one is available.
```
name                old time/op    new time/op    delta
UnmarshalVarchar-4     280ns ± 3%      75ns ± 4%  -73.23%  (p=0.000 n=18+19)
name                old alloc/op   new alloc/op   delta
UnmarshalVarchar-4    1.06kB ± 0%    0.03kB ± 0%  -96.97%  (p=0.000 n=20+20)
name                old allocs/op  new allocs/op  delta
UnmarshalVarchar-4      2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.000 n=20+20)
```
=> marshal: use passed in byte slice if available.

.travis.yml, AUTHORS, cassandra_test.go, conn_test.go, control.go, policies_test.go, session.go, session_test.go
Attempt to solve #1155 
This ended up being a bit bigger than initially expected.
Nevertheless, the majority of work was to update the tests to fetch the correct host they're doing the work for and sending it over as a parameter to other functions. Additionally, it should be somewhat easier to add new metrics to the query execution.
The tests seem to pass successfully now.
@Zariel would love your feedback on this.
=> Query metric per host 1155

conn_test.go, policies.go, query_executor.go, session.go
Solving #1173
* Add a Cancel() call to the ExecutableQuery interface
* Add cancelQuery and cancelBatch fields
* Initiate Query/Batch context/cancel functions
* Implement Cancel() call by calling the cancelQuery/cancelBatch
functions
* Add TestCancel to verify that the query is being cancelled by the
cancel call before it's finished.
=> Allow to Cancel() query at any time

cluster.go, conn.go, conn_test.go
Add an option to switch on write coalescing outgoing requests using
net.Buffers. This can be switched off via cluster config and the
interval to buffer for can be adjusted.
fixes #458
fixes #383
=> conn: implement write coalescing

cassandra_test.go, conn.go, frame.go, integration.sh, session.go
* Moved the customPayload variable from the header to the framer because it's not really part of the header. It's part of the body and can be compressed.
* This PR theoretically allows to set the custom payload in batch and prepare messages but I haven't found a straightforward way for an API to allow this.
=> Allow to set the custom payload

AUTHORS, session.go
Fix the gocql.NewBatch function which is broken due to recent changes and its deprecation. Without this change using the gocql.NewBatch function results in runtime panic like below:
```
2018/09/23 11:08:15 http: panic serving 127.0.0.1:49606: assignment to entry in nil map
goroutine 15 [running]:
net/http.(*conn).serve.func1(0xc000098fa0)
/usr/local/go/src/net/http/server.go:1746 +0x17c
panic(0xb2c720, 0xc74960)
/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/gocql/gocql.(*Batch).getHostMetrics(0xc000284240, 0xc0001509a0, 0xc000208ee8)
/home/marco/godev/gocql/session.go:1478 +0x1ef
github.com/gocql/gocql.(*Batch).attempt(0xc000284240, 0xc000126630, 0xc, 0xbee1f3dffb43c922, 0x221356d3, 0x106cac0, 0xbee1f3dffa8f68ee, 0x215ef6b2, 0x106cac0, 0xc0001e2240, ...) …
```
=> fix usage of deprecated gocql.NewBatch function.

conn.go, conn_test.go
Spinning in the write coalescer when there is no work causes high CPU
load for no reason. Use a second cond to start the flush loop once per
coalesce.
=> conn: avoid spinning in write coalesce with no work

conn_test.go, control.go, policies.go, policies_test.go, query_executor.go, session.go, session_test.go
fixes #1083 
This is an attempt to implement speculative query execution. I think it's more or less covers the feature, but I clearly could have missed some things.
This is still a bit of WIP, so any feedback is welcome @Zariel ( and @annismckenzie if you have the time).
Thanks!
=> Speculative query execution

query_executor.go
This is breaking tests in master. Can you review @alourie ?
=> error if can't retry on more hosts

conn.go, conn_test.go
If the user asks to use compression check that the remote server
supports it by making an options call first.
Rejig conn startup to be self contained.
fixes #1205
=> conn: check we can use compression in startup

cassandra_test.go
Fixes a race condition in TestTracing.
=> tests: fixed a test race in TestTracing

cassandra_test.go, conn.go, conn_test.go, control.go, frame.go, host_source.go, policies.go, query_executor.go, session.go
This also fixes an issue where using WithContext mutated the original
query, it now does what http.Request.WithContext does and returns a
shallow copy of the query.
Rename GetContext() to Context() and have it default o returning
context.Background() when no context has been set.
Use context to cancel speculated queries so they dont leak or run beyond
when one wins.
Fix hiding errors when speculating queries.
Remove explicit query cancelation.
=> query/batch: improve context usage

session.go
Hey, 
I have fix a little typo mistake in documentation `quries` -> `queries`.
=> Fix typo in session.go quries -> queries

marshal.go
I just encountered a bug with `marshalMap` due to a mistake on my part.
Here's a sample which reproduces the bug:
package main
import (
"log"
)
func main() {
cfg := gocql.NewCluster("localhost:9042")
session, err := cfg.CreateSession()
if err != nil {
log.Fatal(err)
}
err = session.Query("CREATE KEYSPACE IF NOT EXISTS ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;").Exec()
if err != nil {
log.Fatal(err)
}
err = session.Query("CREATE TABLE IF NOT EXISTS ks.foobar (id text primary key, data map<text, text>)").Exec()
if err != nil {
log.Fatal(err)
}
const stmt = "INSERT INTO ks.foobar(id, data) VALUES (?, ?)"
err = session.Query(stmt, "foobar", "mystring").Exec()
if err != nil {
log.Fatal(err)
}
}
I get a …
=> marshal: prevent calling IsNil on non nullable types

conn.go, conn_test.go, connectionpool.go
Current write coalescing depends on the idea that the passed in
connection can do the writev syscall.
In Go only net.Conns implemented by the net package have this property,
since that the mechanism requires an implementation of a private method,
checked against an interface private to the net package.
So in practise only real TCP connections implement that.
TLS connections cannot do that either, but that is not handled here.
To get a real tcp connection, I broke up the abstraction of the
deadlineWriter and put the effect of it into the flush call.
To make it clearer that we really need a network connection, I changed
the interface passed in to the clearer net.Conn.
This is just the minimal fix to get writev back. A little cleanup work
is needed too.
Without this fix, we get only delayed …
=> repair write coalescing

conn.go
=> conn: send heartbeats to detect dead connections

AUTHORS, conn.go, conn_test.go
Hosted Cassandra provider [Aiven](http://aiven.io) uses their own authenticator and it causes `gocql` to fail to connect. This just adds it to the approve list with the others.
=> Add Aiven authenticator

host_source.go, metadata.go, session.go
The system.schema_aggregates and system.schema_functions tables don't
exists in 2.1 (these were added in 2.2).
I added a version.AtLeast() function that inverts
version.Before(). Normally you are checking for a minimum version, so
this avoids additional negatives and makes things more readable.
=> Don't fetch aggregates/UDFs on version 2.1

policies.go, session.go, token.go, token_test.go, topology.go
Bug:
`tokenAwareHostPolicy` always selects a primary replica of a token.
When using `tokenAwareHostPolicy` backed by `dcAwareRR`, for tokens
with primary replica in a different DC, this results in selecting
a RANDOM host in a given DC.
This is caused by two issues in `tokenAwareHostPolicy::getReplicas` func.
* `tokenAwareHostPolicy::meta` is always nil unless a keyspace changed
event it received
* even when metadata is available it uses the calculated token value of
a partition key to find replicas, however, the replicas are stored
in a map where the key is the primary replica token aka the `end_token`
(nodetool describering)
Solution:
This commit extends `tokenRing::GetHostForPartitionKey` to return
the endToken that is later used in the `Pick` function, and forces
a call to …
=> policy: tokenAwareHostPolicy host selection bug fix

AUTHORS, query_executor.go
We cannot mark the host as failed in case of logical errors, whether it is from
gocql itself or from the context package.
Ideally, ErrNotFound should not be the only error to be handled, all errors defined in `session.go` should be used.
=> query executor: better handling of errors for host selection

AUTHORS, marshal.go, marshal_test.go
When using version greater than protoVersion2 the range check in
readCollectionSize only checked for two bytes instead of four bytes.
This commit moves the range check inside the function so that it is
near the logic that accesses the buffer.
This is the panic that the missing range check caused:
panic: runtime error: index out of range
goroutine 78088437 [running]:
github.com/gocql/gocql.readCollectionSize(...)
/go/pkg/mod/github.com/scylladb/gocql@v1.0.0/marshal.go:1405
github.com/gocql/gocql.unmarshalList(0xfb2ac0, 0xc003a01900, 0xc008a012d5, 0x2, 0x2f, 0xcf7860, 0xc00632a748, 0x918641, 0x4)
/go/pkg/mod/github.com/scylladb/gocql@v1.0.0/marshal.go:1443 +0xd39
github.com/gocql/gocql.Unmarshal(0xfb2ac0, 0xc003a01900, 0xc008a012d5, 0x2, 0x2f, 0xcf7860, 0xc00632a748, 0xc0073f7130, 0x2) …
=> Fix range checks in readCollectionSize

conn.go, session.go
Currently, control connections used for example to discover protocol
version are not observable using connection observer. This change
aims to make sure all connections created by the driver are seen
by the connection observer.
The `dialWithoutObserver` name is intentionally longer than `dial`
so that one must explicitly acknowledge the connection will not be
observed when using the function.
=> Make sure all connections are observed

helpers.go, marshal.go, marshal_test.go
After discussions it was proposed to treat time as Go time.Duration.
This makes it consistent with what time is in the spec despite it's name.
The discussion took place in https://github.com/gocql/gocql/pull/1283 which was about a panic from incorrectly handling of the cql type time.
The cassandra spec (https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v5.spec#L986) clearly frames this type as a "duration" although the name hints at a "time". It was agreed that using a `time.Duration` instead makes much sense and any cognitive mismatch was negligible.
=> marshalling: treat cql time type as time.Duration

conn.go, host_source.go
Cassandra 2.1 doesn't have any connect address entries in `system.local` table. We parse this table in the driver during initial connection, so the connection to 2.1 fails.
This refactors the `localInfoFromMap` to accept an initial IP address, which simplifies the lookup for an IP.
Fixes #1251 
=> Refactor localInfoFromMap with initial address

conn.go, host_source.go
Improve the way awaitSchemaAgreement queries the peers/local hosts and ignore invalid ones.
Fixes #1298
=> Improve awaitSchemaAgreement

conn.go, frame.go
FrameHeaderObserver is the only observer that does not report
host currently, so add it there as well since Host is useful
if you want to tag the metrics by host/rack/dc/cluster.
=> Add information about Host to FrameHeaderObserver

conn_test.go, session.go
This removes code duplication and ensures the metrics mutex is
locked only once in addAttempts and addLatency.
=> Refactor query metrics code

.travis.yml, README.md
As the README states, the current and previous version of Go is
supported, so tests should be run accordingly.
Also note that this commit removes Go 1.10, the last version
that does not support Go modules.
Thanks @dahankzter for the suggestion.
=> Update supported Go versions to 1.11 and 1.12

conn.go
This is a seemingly trivial change to a plugin whitelist. It uses a drop-in replacement to cassandra username/password auth to create an audit log for compliance purposes.
Edit: To address issue #1320
=> Adding ecaudit plugin to connection whitelist.

policies_test.go, session.go, session_test.go
This will allow the observer to know whether the attempt was
original query or retry.
=> Add attempt number to ObservedQuery

.travis.yml
Go support policy is the latest minor release of the latest two major versions.
In travis, specifying "1.11" pins the test to the original go1.11 release.
=> Test with latest go1.1{1,2} versions

.travis.yml
The 2.1 release branch is [still supported until 4.0 comes out](http://cassandra.apache.org/download/#older-supported-releases), so continue to test against it to ensure compatibility with community supported releases of cassandra.
=> Also test latest 2.1 branch of cassandra

policies.go
This pull request is based on PR https://github.com/gocql/gocql/pull/1328 as I reused some of that code to setup the test to reproduce the issue, so you might want to review that first separately. Only the last commit in this branch is the actual fix, while the one before that adds a test to reproduce the race condition.
The commit description for the last commit follows:
```
Fix updating cluster state in tokenAwareHostPolicy
tokenAwareHostPolicy keeps track of hosts in the cluster, keeps the
token ring and a map of token to replicas that keep the data (which is
computed using a placement strategy).
One issue that is present in old the code is that it updates the host
list and token ring whenever a node goes up or down. While the replica
map is only updated in AddHost/RemoveHost, it could …
```
=> Fix for #1274

common_test.go, policies.go, policies_test.go, session.go
This option allows to fallback to nodes based by token in
remote DCs before falling back to other nodes in local DC.
This is useful in particular when used with
{'class': 'NetworkTopologyStrategy', 'a': '1', 'b': '1', 'c': '1'}
Other commits in this PR mainly add tests.
=>  Add NonLocalReplicasFallback option to TokenAwareHostPolicy

.travis.yml, README.md, cassandra_test.go, common_test.go, integration_test.go
```
Fix tests in Go 1.13
The flag.Parse() in common-test.go init() causes errors to be raised
since package testing no longer registers it's flags in its own init(),
but instead provides testing.Init().
One option to fix this is to call testing.Init() just before calling
flag.Parse(). However, testing.Init() is not available in older Go
releases so we'd need to create separate versions of init() based on
build tags.
Instead, we can remove the call to flag.Parse() altogether as it was
only used to set clusterHosts variable and we defer parsing of
clusterHosts to a time when tests are executed. This version of code
runs both on Go 1.12 and Go 1.13.
```
```
Test with Go 1.13 and 1.12 in CI
As per the README: In general, the gocql team will focus on supporting
the current and previous …
```
=> Test with Go 1.13 and 1.12 in CI 

common_test.go, conn_test.go, control.go, host_source.go, marshal.go, marshal_test.go, policies.go, policies_test.go, session.go, token.go, topology.go, topology_test.go
We are not going to have every token in a map, instead binary search to
find the closest host which owns the token. This remove the need to
first binary search the tokenRing to find an actual token to lookup in
the map.
Fix SimpleStrategy not placing replicas on unique hosts.
Dont return duplicate hosts from fallbacks from TokenAwarePolicy
go fmt ./...
updates #1349, #1316
=> topology: replace token map with binary search

policies.go, policies_test.go, topology.go
Instead of keep a global position to iterate around a ring of hosts just
shuffle all the hosts and return hosts which are up.
Fix finding the correct token in the token ring for host selection.
Simplify the tests so that they only test things they are inteded to
test, let other tests verify that DCAwareRR works for example.
=> policy: roundrobbin should try all up hosts

policies.go, session.go
Adding a new host to the TokenAwarePolicy requires recomputing the
replica map, previously we would add each host one at a time which
requires regenerating the replica map for each host and discarding the
old one. Fix this to only calcaulte it once during init after adding all
the hosts in a bulk operation.
=> session: bulk add hosts to TokenAwarePolicy on init

common_test.go, go.mod
I get a lot of timeouts when running integration tests and simply setting a retry policy for the createTable() testing method seems to make it much more reliable.
=> Increasing local test stability

integration.sh
Local stability increased by clearing the database before running
integration tests.
=> testing: increase local run reliability further

host_source.go
This ends up associating the wrong connectAddress with each peer since we
don't overwrite connectAddress inside hostInfoFromMap.
Fixes #1361
=> Don't send connectAddress when looping over peers

cassandra_test.go, session.go
Paging state was not reset in query::Bind which effectively broke
paging when Bind was used.
Fixes: #1364
=> query: fixes pagination with query binding

marshal.go, marshal_test.go
There were a few inconsistencies with unmarshaling to unsigned integers:
- negative values were not range checked for primitive uint types
- negative values were not allowed at all for named uint types
This commit restricts the range of accepted values so that we marshal
the same value as we unmarshal. We accept negative values for a type
only if the width of cql type is smaller or equal than the width of Go
type. This ensures that unmarshaling is bijection from CQL to values
to Go values, without the check the following situation can happen:
- we unmarshal CQL smallint 0xffff (-1) to Go uint8 0xff
- we unmarshal CQL smallint 0x00ff (255) to Go uint8 0xff
- we marshal uint8 0xff to CQL smallint 0x00ff (255)
Therefore smallint value -1 would be turned into 255 during round-trip.
We also …
=> Fix unmarshaling to unsigned integers

conn.go, conn_test.go, connectionpool.go, control.go, session.go
If a callers context is cancelled and they won the race to prepare a
statement, dont stop the prepare and fail it with context failed error
as other callers may be waiting for us to finish.
Achieve this by replacing the waitgroup used to wait for prepared to
finish with a channel which is closed by the preparer. Do the preparing
in a goroutine and use context.Background in the exec call so that the
prepare will always finish. All callers now use the same flow to wait
for the result of the prepare waiting against their own context so they
can bail out individually.
fixes #1341
=> conn: dont propogate context cancelled in prepare

policies.go
`ExponentialReconnectionPolicy` doesn't honor the number of retries made, since it uses the wrong argument for the attempt count.
Test code:
```
package main
import (
"fmt"
)
func main() {
policy := gocql.ExponentialReconnectionPolicy{
MaxRetries: 10,
}
for index := 0; index < 10; index++ {
fmt.Println(policy.GetInterval(index))
}
}
```
Before changes:
```
51.210466028s
51.244050908s
51.216456005s
51.193771418s
51.192463749s
51.218682307s
51.156563701s
51.165651925s
51.159696951s
51.180091186s
```
After changes:
```
60.466028ms
144.050908ms
216.456005ms
393.771418ms
792.463749ms
1.618682307s
3.156563701s
6.365651925s
12.759696951s
25.580091186s
```
=> Fix ExponentialReconnectionPolicy not incrementing correctly

conn.go, conn_test.go
Signed-off-by: Pedro Silva <pedro.silva@softruck.com>
AWS Managed Cassandra Service needs the HelenusAuthenticator.
=> [feature] AWS HelenusAuthenticator

conn.go
The error handling for retrying or erroring out upon failure to find a server side prepared statement now simply attempts to prepare and execute again.
Fixes: #1252
=> conn: unconditionally retry query execution on errUnprepared

conn.go, prepared_cache.go
Ensure we only remove prepared statements on ErrUnPrepared when our
cached statements ID matches the unprepared statement.
fixes #1390
=> conn: fix race evicting statements on ErrUnPrepared

integration_test.go, session.go
This adds `AwaitSchemaAgreement` to the `*gocql.Session` object by using the control connection and the already existing `awaitSchemaAgreement` functionality on the Connection object.
See https://github.com/scylladb/gocqlx/issues/106 and https://github.com/gocql/gocql/issues/1301 for details.
=> Add AwaitSchemaAgreement to Session

policies.go
With ShuffleReplicas enabled, we were shuffling an empty list of
replicas and not doing any token aware routing.
=> Fix token aware host policy.

policies.go
since the default of around every 9 hours is a bit too high for most use cases.
e.g. you actually want to give the ops team up to 24 hours to recover a
node, but want to confirm normal operations quickly after they are done.
=> Add ExponentialReconnectionPolicy.MaxInterval

policies_test.go, topology.go
We've seen increased per-query latency after upgrading to latest gocql.
This commit fixes the latency issue for us.
This partially reverts 7b17705d75148afe48e336a49743178a201cdda3. There
were multiple unrelated changes in that commit. The relevant part of
that commit's description is:
Fix finding the correct token in the token ring for host selection.
Unfortunately that description does not contain the details of the issue
it was aimed to fix.
The change in 7b17705d75148afe48e336a49743178a201cdda3 also made the two
binary search implementations (tokenRingReplicas.replicasFor and
tokenRing.GetHostForToken) inconsistent, reverting the change fixed this
discrepancy as well.
The token values returned in system.peers and system.local tables are
ends of ranges that the nodes are responsible …
=> Fix selection of host by token

policies.go
Copy-free and allocation-free version of round robin.
Uses offset increased by atomic package to select next query destination.
Fixes memory allocation in #1401 downing it to zero.
=> Allocation-Free Round Robin Policy (fixes #1401)

token.go, token_test.go
This function is not used anymore.
=> Remove tokenRing.GetHostForPartitionKey

conn.go, session.go
Control queries only ever do reads on system tables but AWS MCS treats a
prepare as write which it blocks on system tables. We can avoid doing
prepares on selects as long as we get the result metadata.
fixes #1389
=> conn: add skip prepare for control queries

AUTHORS, topology.go, topology_test.go
Keyspace could define replication that doesn't cover all datacenters.
More over: such case certainly happens when new data is added to cluster.
This commit fixes handling of this situation in networkTopology replicaMap
by skipping tokens from excess datacenters.
fixes #1349
=> allow tokenAware policy to handle keyspace with skipped dcs

session.go
ObservedQuery and ObservedBatch expose a pointer to hostMetrics struct
to the respective observers. However, the fields of the returned
*hostMetrics are not safe to read, since the observer that might access
hostMetrics' fields is called without the lock held.
In order to return a safe value to clients, we need to make a copy of
the hostMetrics struct while the lock is still locked.
This commit also optimizes the count of lock/unlock calls, previously we
did 3 pairs (for updating attempts, for updating latency and for getting
hostMetrics), now we only do one.
=> Fix data race when accessing hostMetrics

conn.go
The CreateSession with consistency and keyspace supplied will trigger a `use keyspace` query.
However, this query does not use the consistency supplied, instead it uses `Consistency.Any`.
This cause issue when using it with AWS MCS where only `Consistency.LocalOne` or `Consistency.LocalQuorum` is accepted for read statement
=> CreateSession use statement consistency

marshal.go, tuple_test.go
In case the tuple value has never been written the unmarshalling
used to panic. This is now handled by inspecting the data from the
database and if it is missing (nil) it will set the tuple value to
the corresponding default value.
Fixes: #1343
=> tuples: correct unmarshalling of unset tuple values

AUTHORS, helpers.go, helpers_test.go
Fixes #1430 .
Small fix and added some more coverage for `tinyint` as well.
=> Parse smallint data type in metadata

marshal.go, marshal_test.go
There were missing checks for length which could lead to panic when the
server sends malformed data. This commits adds the missing checks.
=> Add eof checks to unmarshalList/Map

conn.go
To address issue https://github.com/gocql/gocql/issues/1440.
This is a trivial change to add a new authenticator of an existing plugin - ecaudit to the whitelist.
=> Adding ecaudit.auth.AuditAuthenticator to connection whitelist.

cassandra_test.go, common_test.go, metadata.go, metadata_test.go
Fixes https://github.com/gocql/gocql/issues/1435
=> fix metadata views, incorrect query

conn.go, session.go
I executed
$ gofmt -w *.go
locally. This came out of https://github.com/gocql/gocql/pull/1456 where
my editor proposed making certain format changes.
Have you considered adding a linter to make sure PRs are properly linted
according to `gofmt`?
=> style: gofmt all files

session.go
...for full sentence comment. This makes the comment consistent with the
rest of the documentation.
=> docs(session): add missing full stop

marshal.go, marshal_test.go
There are two problems.
First, tuples with a null value are not handled properly which results in a
panic:
panic: runtime error: slice bounds out of range [:-1]
goroutine 1 [running]:
github.com/gocql/gocql.unmarshalTuple(0x769880, 0xc0000e8cc0, 0xc0000ae83a, 0x10, 0x4a, 0xc000186540, 0xc000190480, 0xc000190480, 0x16)
/home/vincent/dev/go/src/github.com/gocql/gocql/marshal.go:1950 +0x1276
github.com/gocql/gocql.Unmarshal(0x769880, 0xc0000e8cc0, 0xc0000ae836, 0x10, 0x4a, 0xc000186540, 0xc000190480, 0xc0000e8cc0, 0xc0000ae832)
/home/vincent/dev/go/src/github.com/gocql/gocql/marshal.go:167 +0xd56
github.com/gocql/gocql.unmarshalMap(0x769800, 0xc0000e8d00, 0xc0000ae836, 0x10, 0x4e, 0x698740, 0xc000190450, 0x0, 0x677f11)
/home/vincent/dev/go/src/github.com/gocql/gocql/marshal.go:1669 +0x8fb …
=> fix tuple unmarshaling

marshal.go, marshal_test.go
Hello,
this PR fixes the marshaling of null values in tuples.
Right now for a null value gocql writes a length of `0` but a null value should be encoded as a `-1` [as per the CQL spec](https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v4.spec#L208-L209).
Writing `0` breaks cqlsh sometimes:
```
Traceback (most recent call last):
File "/home/vincent/dev/Batch/Ops/cassandra/bin/cqlsh.py", line 1050, in perform_simple_statement
result = future.result()
File "/home/vincent/dev/Batch/Ops/cassandra/bin/../lib/cassandra-driver-internal-only-3.11.0-bb96859b.zip/cassandra-driver-3.11.0-bb96859b/cassandra/cluster.py", line 3925, in result
raise self._final_exception
DriverException: Failed decoding result column "prev_generation_id" of type set<frozen<tuple<timeuuid, timestamp>>>: …
```
=> Fix tuple marshaling

.travis.yml, README.md
We support two latest versions of Go.
=> Support Go 1.14 and 1.15

session.go
We have attempt count in ObservedQuery, add it to ObservedBatch as well
for feature parity.
=> Add Attempt count to ObservedBatch

batch_test.go, session.go
With just timestamp int64 parameter, it's possible to mistake the unit
used for the timestamp, so we document that it's microseconds since UNIX
epoch.
Since Go users are likely to already have a time.Time value representing
the time instant used for the timestamp, I'm adding a method that
accepts a time.Time directly and takes care of the correct unit
conversion itself.
=> Add a variant of WithTimestamp that accepts time.Time

AUTHORS, session.go
We have some problems with code `go iter.next.fetch()` from `iter.Scan`. Under heavy load it creates too many goroutines.
```
func (iter *Iter) Scan(dest ...interface{}) bool {
...
if iter.next != nil && iter.pos >= iter.next.pos {
go iter.next.fetch()
}
```
In our performance test ~800 reading routines created 1 842 734 (!) almost 2M fetching routines. It is too heavy load for runtime :)
```
814 @ ...
#	0x6ba9c8	github.com/gocql/gocql.(*Conn).exec+0x448
#	0x6bbae8	github.com/gocql/gocql.(*Conn).executeQuery+0x568
#	0x70f128	github.com/gocql/gocql.(*Query).execute+0x48
#	0x708163	github.com/gocql/gocql.(*queryExecutor).attemptQuery+0x83
#	0x708c46	github.com/gocql/gocql.(*queryExecutor).do+0x1c6
#	0x7086cd	github.com/gocql/gocql.(*queryExecutor).executeQuery+0xed
#	0x70c9b1 …
```
=> Avoid creating extra goroutines on nextIter

.github/issue_template.md
Some issues might be reproducible only using specific
Go version. If someone is not using latest Go version,
we might want to ask them to upgrade and try to reproduce.
This change is inspired by the following comment:
https://github.com/gocql/gocql/issues/1481#issuecomment-728758618
=> Add Go version to issue template

AUTHORS, control.go
Just adding port number into "unable to dial control conn" error message to simplify debugging
=> Add port number into error message

marshal.go, marshal_test.go
If unmarshalUUID called with value of type gocql.UUID, we already have allocated bytes for UUID, so do not allocate extra UUID, but just copy data to value. 
Also add ability to unmarshal directly to array of 16 bytes.
=> Do not allocate extra bytes in unmarshalUUID

marshal_test.go
In 179bae5f16901945ab66d7c2d9088dc4282281c4 we changed the error
message from upper case to lower case, but the test was not updated.
I don't know whether I missed failing CI build when merging or
whether CI did not run at all.
Anyway, this commit fixes the test.
=> Fix TestMarshal_Decode

marshal.go
It was not documented anywhere how cql data types map to Go
data types.
I haven't included data for exact cases when type aliases are
supported.
=> Document type conversions for Marshal and Unmarshal

policies.go, query_executor.go
Before this commit, regular query execution path and speculative
execution path did not use the same host iterator.
This means that speculative execution could retry on the same
host as the original attempt. This could lead to overloading that
slow host even more instead of trying on some other host if
the policy consistently selects that host (for example based on
token).
We fix this by sharing the host iterator returned by the host selection
policy. The returned iterator could now accessed from multiple
goroutines, so we need to synchronize access to it. I chose this instead
of implementing synchronization in each policy because I can't fix
any user-provided policies. Synchronizing in the driver avoids
introducing new data race for user-provided policies as those likely
won't be …
=> Use the same host iterator in speculative execution

conn.go, conn_test.go
It does not make sense to send requests where the results will
be immediately discarded. In fact, it can be harmful in situations
where a lot of contexts are canceled (e.g. because of timeouts).
=> Don't do network IO with already canceled context

conn.go, session.go
Currently the attempt count in query metrics is incremented both on
retries and when fetching next page, making it impossible to track just
the retry count. By shallow-copying the query and changing the metrics
we ensure that attempts are counted per-age (so attempts>0 means always
a retry).
We were copying the Query previously
(before 271c061c7f16702ca550b0e9721320b1c92e00cb), but I don't know why
exactly the copying was removed there.
In any case we can't change the paging state in the original Query
because there might be a separate goroutine spawned by speculative
execution that accesses the field. Even if we added a lock around
Query.pagingState field, the speculative execution could try to fetch
different page.
We could possibly move pagingState and metrics to nextIter or other …
=> Copy query when fetching next page

doc.go
In the short introduction on how to connect to a cluster there was a small typo for a ClusterConfig option, fixed with this PR.
=> Fixed small typo in documentation

topology.go, topology_test.go
In case a network topology strategy with zero replication factor
for at least one DC is encountered, the driver panicked with
token map different size to token ring.
This is because len(dcRacks) includes the datacenters where replication
factor is zero, but these datacenters should not have any replicas.
=> Fix panic in replicaMap when rf=0

AUTHORS, cassandra_test.go, session.go
The statements passed in the statement fields of ObservedQuery and ObservedBatch, do not account for the bound values passed while executing a query. 
Refer issue: #1497 for more details
=> Bound values added in fields of ObservedQuery and ObservedBatch struct

cluster.go, conn.go, conn_test.go, connectionpool.go, control.go, events.go, events_test.go, filters.go, helpers.go, helpers_test.go, host_source.go, logger.go, metadata.go, metadata_test.go, policies.go, session.go, session_test.go, topology.go
There are race conditions in tests that swap the global logger,
we shouldn't modify any global state in tests or otherwise.
=> Add per-session logger

connectionpool.go, control.go, events.go, host_source.go, session.go
After merging https://github.com/gocql/gocql/pull/1369 it could happen
that after losing connection to a host, it is not reconnected.
That could happen in the following case:
1. We lose connection to a host.
2. We receive UP event for the host, the host is marked as UP even
though we don't have active connections to it.
3. We don't reconnect to the host in reconnectDownedHosts because it's
marked as UP already.
In PR 1369 we intended to change the host states so that a host is
marked as UP only after we have some connection to it. However, we also
removed the call to fill the pool on UP event in case the host already
existed.
This commit adds the call to fill the pool back to handleNodeUp.
We introduce handleNodeConnected for marking the host as up,
so that handleNodeUp handles only the …
=> Fix reconnecting to cluster

compressor.go, compressor_test.go, go.mod, go.sum, lz4/go.mod, lz4/go.sum, lz4/lz4.go, lz4/lz4_test.go
Some users have problems using gocql/gocql with dep as
dep can't work with v4 dependency.
Moving the lz4 compressor to a separate module.
This is a breaking change, but there probably aren't many
people using the lz4 compressor yet.
=> Move lz4 compressor to separate module

AUTHORS, metadata.go
Discovered while trying something along the lines of https://play.golang.com/p/kMijXA7kW0E, i.e.
```
a := gocql.DESC
if someCondition() {
a = gocql.ASC
}
```
https://go.dev/ref/spec#Constant_expressions says only the expression part repeats and gives
```
const (
u         = iota * 42  // u == 0     (untyped integer constant)
v float64 = iota * 42  // v == 42.0  (float64 constant)
w         = iota * 42  // w == 84    (untyped integer constant)
)
```
=> Make DESC a ColumnOrder, not a bool

.travis.yml, AUTHORS, README.md
Update go version from 1.15, 1.16 to 1.16, 1.17.
=> Update supported go version in build matrix

.github/workflows/main.yml, README.md
Go 1.18 was released, let's test with 1.17 and 1.18 as those
are the only supported versions of Go now.
=> Run tests with Go 1.18

cluster.go, conn.go, session.go
This allows to get metrics like current count of inflight streams.
A StreamObserver that does not want to store any context per stream
can always return the same value.
=> Add ability to observe streams

marshal.go, marshal_test.go
reflect.Value.Elem panics when the value is not a suitable type.
In all other places we check that we received a pointer value,
but the check was missing in unmarshalUDT.
We want to return an error instead of the panic that happened
previously:
```
panic: reflect: call of reflect.Value.Elem on map Value [recovered]
panic: reflect: call of reflect.Value.Elem on map Value
goroutine 6 [running]:
testing.tRunner.func1.2({0x72af00, 0xc00000e150})
/usr/local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1212 +0x218
panic({0x72af00, 0xc00000e150})
/usr/local/go/src/runtime/panic.go:1038 +0x215
reflect.Value.Elem({0x72dd60, 0xc000108f00, 0xc000108f00})
/usr/local/go/src/reflect/value.go:1178 +0x15a
github.com/gocql/gocql.unmarshalUDT({0x801eb0, …
```
=> Add check for pointer kind to unmarshalUDT

helpers.go, marshal.go
When there is no corresponding Go type available,
unmarshaling panics. We want to return an error instead.
Unfortunately, TypeInfo.New() can't return an error.
We can't change the signature of New as it might be used
externally. For New(), the only option is to keep panicking.
We now at least provide a more useful panic message.
We are adding a new method to interface TypeInfo that returns
as error instead of panicking. Changing the interface is a
breaking change for users that implement custom TypeInfo.
I don't expect any custom implementations of this interface
though, so I think this change is safe.
An alternative to adding the method to the interface would
be to add a separate interface and a function to use the
new interface when available, with fallback to TypeInfo:
type TypeInfo2 …
=> Don't panic when there is no Go type available

control.go, integration_test.go, ring.go
Check the HostFilter when making the control connection. This allows you to filter out connecting to the wrong DC or an undesirable host for the control connection. This also has the benefit of allowing the HostFilter to modify the ConnectAddress which fixes #1608.
If you filter out the chosen host for the control connection then we'll try another one until we've exhausted all hosts.
=> Check HostFilter for control connection

cluster.go, policies.go
Sharing a policy between sessions is not supported because the policy
receives state updates from the session.
Let's update the documentation and add a panic in TokenAwareHostPolicy
constructor. It is better to panic early than to have races and
undefined behavior later.
See also discussion in https://github.com/scylladb/gocql/issues/94
=> Make sure policies are not reused between sessions

.github/workflows/main.yml
This should fix CI that fails because of URISyntaxException in nodetool
(CASSANDRA-17581).
=> Upgrade Cassandra versions used in CI

AUTHORS, marshal.go, marshal_test.go
Handle `nil` values for supported protocol versions when (un)marshalling lists and maps according to the specs:
```
6.11 list
A [int] n indicating the number of elements in the list, followed by n
elements.  Each element is [bytes] representing the serialized value.
6.12 map
A [int] n indicating the number of key/value pairs in the map, followed by
n entries.  Each entry is composed of two [bytes] representing the key
and value.
```
```
[bytes]        A [int] n, followed by n bytes if n >= 0. If n < 0,
no byte should follow and the value represented is `null`.
```
=> Handle nil values when (un)marshalling lists and maps

cluster.go
This change is to make maintanance easier.
With comments above the fields, each field is indented separately,
so we can insert new fields into the struct and update the documentation
comments without gofmt reformating the whole struct.
This should reduce diffs in commits and minimize conflicts when
merging to forks.
=> Reformat ClusterConfig to have doc comments above fields

cassandra_test.go, conn.go, connectionpool.go, events.go, host_source.go, prepared_cache.go, ring.go, ring_test.go, session.go, uuid.go
Currently driver identifies nodes based on their broadcasted IP
address. In cloud case, broadcasted IP addresses are private and are not
meant to be used as a contact point, and they may change overtime.
Hence driver internals were changed to identify nodes based on their
host_id which is unique per node and it's persistant throught entire
node lifecycle.
Because CQL Events are still using broadcasted IP addresses, driver
keep mapping between already known IP addresses and host_ids.
Prepared statement cache key was also changed to host_id, to not
invalidate it upon IP change.
=> Identify nodes by their host_id instead broadcasted_address

marshal.go, marshal_test.go
We can't return an error in case a field is added to the UDT,
otherwise existing code would break by simply altering the UDT in the
database. For extra fields at the end of the UDT, we can either omit
them or put nulls.
The Java driver[1] and Python driver[2] serialize nulls when they
don't have a value for a field even for fields in the middle, so let's
do that. This behaviour matches even gocql when serializing structs.
[1] https://github.com/datastax/java-driver/blob/ef56d561d97adcae48e0e6e8807f334aedc0d783/core/src/main/java/com/datastax/oss/driver/internal/core/type/codec/UdtCodec.java#L86
[2] https://github.com/datastax/python-driver/blob/15d715f4e686032b02ce785eca1d176d2b25e32b/cassandra/cqltypes.py#L1036
=> Marshal missing UDT fields as null instead of failing

marshal.go
We know the number of elements in the map in advance, so we can
preallocate the map to avoid allocations when growing.
=> Allocate map with the initial size during unmarshal

conn.go, helpers.go, host_source.go
As currently implemented `system.peers_v2` support doesn't work for DSE
clusters because it returns 4.0.x for the `release_version`. This
attempts to use the `system.peers_v2` table when `release_version` is >=
4.0.x, but falls back gracefully to `system.peers` when that table isn't
found.
=> Fallback to `system.peers` when `system.peers_v2` is not available

AUTHORS, session.go
iter.GetCustomPayload() causes a nil panic if an error occurs on the cassandra query as iter.framer is nil. This PR adds a nil check of the framer before accessing customPayload and returns nil in the case where the framer is nil. This is similar to how Warnings() function works.
=> ensure framer is not nil before accessing customPayload

AUTHORS, events.go
For the moment we have unsafe coding where we try to use `host` object
before checking the success of it's `get` operation.
When a DB node gets forcibly terminated we have a race condition
to get the following panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x632814]
goroutine 1723 [running]:
github.com/gocql/gocql.(*HostInfo).HostID(0xc0001500b8)
%full-path%/host_source.go:253 +0x34
github.com/gocql/gocql.(*Session).handleRemovedNode(
0xc000150000, {0xc0134c10d8, 0xc0093d69b0, 0xa}, 0x45264d)
%full-path%/events.go:243 +0x5f
github.com/gocql/gocql.(*Session).handleNodeEvent(
0xc000150000, {0xc01701a000, 0x1, 0x43e305})
%full-path%/events.go:176 +0x28e
created by …
```
=> Fix nil pointer dereference in events.go handling node removal

.github/workflows/main.yml, CHANGELOG.md, README.md
We generally support the last two stable versions of Go,
updating the CI to test against them.
=> Use Go 1.19 in CI

README.md
Update build badge and build matrix from README docs. 
Also, remove the `.travis.yml` file as it's not part of CI anymore.
=> docs: Update build badge and build matrix

AUTHORS, CHANGELOG.md, conn_test.go, doc.go, policies.go, policies_test.go
I wrote 90% of this code, then realized that there's already a somewhat stale PR for the same issue open as #1565.
The rationale behind this PRs is the same: cassandra running on public clouds tend to use what AWS calls "region" as cassandra datacenter, and "availability zone" as rack.  A common desire is to keep traffic with-in the current AZ whenever possible from both a performance and cost standpoint.
This PR adds a `HostTierer` interface.  This is extremely similar to the `HostDistancer` interface suggested in the referenced PR, except that I feel like Tier more accurately reflects that we're grouping hosts into bins, not simply coming up with a cost metric (e.g. distance = ping RTT).
The `TokenAwareHostPolicy` now support an arbitrary number of tiers.  It will check to see if the …
=> Rack aware host selection policy

policies_test.go
Most of the tests were missing checks that the list of hosts is finished, this commit adds them.
Removed checkList so that all tests look similar.
=> Check all hosts in host selection policy tests

policies.go
When updating Debian packaging to 1.3.0, we noticed that tests were failing on 32-bit systems e.g. on 32-bit ARM [1] or i386 [2]:
```
=== RUN   TestHostPolicy_RackAwareRR
--- FAIL: TestHostPolicy_RackAwareRR (0.00s)
panic: unaligned 64-bit atomic operation [recovered]
panic: unaligned 64-bit atomic operation
goroutine 96 [running]:
testing.tRunner.func1.2({0x27b5b8, 0x30a408})
/usr/lib/go-1.19/src/testing/testing.go:1396 +0x27c
testing.tRunner.func1()
/usr/lib/go-1.19/src/testing/testing.go:1399 +0x3f4
panic({0x27b5b8, 0x30a408})
/usr/lib/go-1.19/src/runtime/panic.go:884 +0x23c
runtime/internal/atomic.panicUnaligned()
/usr/lib/go-1.19/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Xadd64(0x181267c, 0x1)
/usr/lib/go-1.19/src/runtime/internal/atomic/atomic_arm.s:258 …
```
=> Fix alignment bug on 32-bit platforms in new `rackAwareRR` code

AUTHORS, events.go
The current issue is that there are no events dispatched for `NEW_NODE` changes. In a 3 node cassandra cluster deployed on cloud infrastructure, a cassandra instance was replaced using the `replace_address` flag so that it was moved to a new cloud instance (new IP, new host ID). The following debug logs are an example of how the client is currently handling this change in topology. 
```
2023/01/11 20:59:35 gocql: handling frame: [topology_change change=NEW_NODE host=10.128.191.122 port=9042]
2023/01/11 20:59:35 gocql: handling frame: [status_change change=UP host=10.128.191.122 port=9042]
2023/01/11 20:59:35 gocql: dispatching event: &{change:UP host:[10 128 191 122] port:9042}
2023/01/11 20:59:35 gocql: Session.handleNodeUp: 10.128.191.122:9042
```
There is no event dispatched for the …
=> refresh ring when node UP event received for missing host

AUTHORS, CHANGELOG.md, events.go, host_source.go
With existing behavior, when a Cassandra node changes its IP address (while keeping the same host ID), the gocql client never utilizes that new IP address.  In the event ALL nodes change their IP addresses (over the lifetime of the gocql client), the cluster connection will become unusable.  Attempts to query Cassandra will be met with `gocql: no hosts available in the pool` errors.
I am experiencing this behavior connecting to a Cassandra cluster running on Kubernetes.  When a rolling restart occurs (StatefulSet change or otherwise), many of my long-lived gocql clients will become unresponsive.  Restarting the affected processes is required to restore Cassandra connectivity.
With these changes in place, when a `NEW_NODE` message is received for an existing host (host ID) with a new IP …
=> Fix k8s reconnect

session.go
We switched from separate mutex for closing to sessionStateMu in 312a614907c8d2e19f6b14aff16015436cb78423.
This change introduced a deadlock.
We don't need to hold the mutex for the whole duration of Close(), we only need to update the status atomically.
Previously IsClosed() returned true only after all closing is done (because of the deferred unlock).
We can emulate that by setting isClosed at the end of Close(). We need a new variable to ensure that Close() is only executed once.
Fixes https://github.com/gocql/gocql/issues/1687
=> Fix a deadlock in Session.Close() during control connection reconnect

AUTHORS, CHANGELOG.md, query_executor.go, session.go
As described in #1315, there is a race condition when there is more than one concurrent execution (by means of speculative execution) and `Query.Release()` is called after one of them completes. `Query.Release()` calls `Query.reset()`, which in turns zeroes the whole `Query`. Then, after another execution completes, it tries to access metrics, but they are already set to nil by the call to `Release()`, so a segfault is triggered.
The solution is quite simple: a ref counter is introduced into the `Query`. It is obviously initially set to 1. Every execution fiber (i.e. every execution goroutine) has the refcount atomically incremented before it is started, and decrements the refcount on completion. `Query.Release()` merely decrements the refcount. `Query.reset()` is called by whichever …
=> query_executor: Fixed race between Query.Release() and speculative executions

AUTHORS, conn.go, control.go, control_ccm_test.go, events.go, host_source.go, host_source_test.go, internal/ccm/ccm.go, session.go
Currently, there are some cases where gocql does not refresh the ring during a control connection reconnection. If topology changes are happening on the cluster during the reconnection, some `NEW_NODE` and `REMOVED_NODE` protocol events might be missed. 
To fix this, every successful reconnection on the control connection should trigger a ring refresh operation. This PR adds that.
Also, this PR fixes an issue where `NEW_NODE` events can be overwritten by `UP` events and cause certain nodes to not be added to the ring. This is an issue already described in #1669 but the fix proposed by this PR is a bit different than one outlined on that PR. This PR causes any topology event to trigger a ring refresh regardless of how many nodes were removed or added. This eliminates the need to have …
=> Always refresh ring on topology changes and reconnections

AUTHORS, dial.go, host_source.go
When a hostname resolves to multiple hosts, multiple HostInfos are generated. DialHost must connect to the host received as parameter. If the hostname is used to establish the connection, the dns could resolve to another host.
The hostname should still be used to verify the TLS connection.
=> DialHost must connect to the requested host

AUTHORS, CHANGELOG.md, marshal.go, marshal_test.go
Fixes https://github.com/gocql/gocql/issues/1693
List of issues:
- `unmarshalUDT`, can cause panic of data is not aligned with udt structure
- `unmarshalMap`, potential wrong result if `readCollectionSize` return negative size
- `unmarshalList`, otential wrong result if `readCollectionSize` return negative size
- `decVint`, potential panic if data is not aligned
- `decVints`, potential panic if data is not aligned
- `unmarshalDecimal`, potential panic if data is not aligned
=> Fix potential crashes on deserealization

AUTHORS, marshal.go, marshal_test.go
We are using nanosecond precision when reading a `TypeDate` into a `time.Time` value, this limits the dates we can accurately read and write from cassandra to `[1677-09-22, 2262-04-11]` since outside of this range we end up with integer overflow. Dates outside of this range encode correctly and are persisted in Cassandra, but are then read as an incorrect value.
The new supported date range is `[-5877641-06-23, 5881580-07-11]` given that we are decoding the epoch day as a 32 bit int (`-2147483648` = minimum int = `-5877641-06-23`). I think it's possible to expand the range if ever needed by decoding a 64 bit int and using `time.Unix(seconds, 0)`, but I didn't think it was worth looking into that change.
Please let me know if I missed anything from the testing.
=> Support larger dates in TypeDate marshalling

conn.go, version.go
Advertising driver's name in the system.clients table can be helpful when debugging issues, e.g. when a connection imbalance occurs and allows to narrow down the culprit application/driver better.
The main module name is stored in a const in version.go.
The replaced module name and the version are fetched from the binary runtime information, where it comes from GitHub metadata (release tag).
Credits to @zimnx for this idea!
I've tested this manually using my fork. The version has shown correctly in system.clients.
=> conn: Advertise driver's name & version in STARTUP

session.go
In the context of `gocql` itself there is little point for this method. But when building wrappers for `Query` the `values` cannot be accessed by the wrapper. This becomes interesting for wrappers that implement functionality like `BindStruct`. A wrapper would need to keep track of the values itself. While this is possible, a wrapper of a wrapper cannot access the values any more if neither `qocql` nor the wrapper expose them.
This little addition to the library would help significantly in the creation of custom build wrappers that want to rely on the stability of this package as a foundation.
=> Add method to Query to be able to retrieve the Values

control.go, host_source.go, session.go
If all nodes in the cluster change their IPs at one time, driver used to no longer be able to ever contact the cluster; the only solution was to restart the driver. A fallback is added to the control connection `reconnect()` logic so that when no known host is reachable, all hostnames provided in ClusterConfig (initial contact points) are reresolved and control connection is attempted to be opened to any of them. If this succeeds, a metadata fetch is issued normally and the whole cluster is discovered with its new IPs.
For the cluster to correctly learn new IPs in case that nodes are accessible indirectly (e.g. through a proxy), that is, by translated address and not `rpc_address` or `broadcast_address`, the code introduced in #1682 is extended to remove and re-add a host also when its …
=> Reresolve hostnames as fallback when all hosts are unreachable

AUTHORS, CHANGELOG.md, conn.go, conn_test.go
Hi,
Just adding opening a small PR to add the InstaclustrPasswordAuthenticator to the default approved list of authenticators in the gocql project.
This would be beneficial for us, as customers of ours using your driver have to do some additional configuration steps in-order to use an Instaclustr managed Apache Cassandra 4 cluster.
If you have any questions or concerns please let me know.
=> Add instaclustr password authenticator to default approved list

CHANGELOG.md, conn.go, conn_test.go
These are already allowed in github.com/scylladb/gocql.
Closes https://github.com/gocql/gocql/issues/1703
=> Add Scylla authenticators to approved list

AUTHORS, CHANGELOG.md, cass1batch_test.go, conn.go, frame.go, keyspace_table_test.go, policies_test.go, query_executor.go, session.go, session_test.go
Previously  `gocql.TokenAwareHostPolicy` always used keyspace explicitly specified in `.Keyspace` in `ClusterConfig` regardless of the keyspace in the Query. This would mean that the token awareness feature would not work properly if the user did not specify `.Keyspace` in `ClusterConfig` or did a query to a different keyspace.
This PR introduces transferring Keyspace and Table names to the Query from the PREPARED response  and updating information about that every time this information is received. After this change, the token awareness feature can work properly without user having to specify a keyspace in `ClusterConfig`.
I created automated integration test ( `keyspace_table_test.go`) on 3 nodes cluster. 
Fixes: #1621
=> Update Keyspace/Table name in prepared Query statement

session.go
Previously there was no information about shards/threads in tracing. It could be problematic, if we want to test shard/thread related features. 
This PR introduces adding information about shard/thread to the tracing. This information could be needed for testing shard awareness. Also it is more in line with `cqlsh` tracing.
In Cassandra single tracing event looks like that:
```
session_id                           | event_id                             | activity                                    | source    | source_elapsed | source_port | thread
-------------------------------------+--------------------------------------+---------------------------------------------+-----------+----------------+-------------+-----------------------------
568f2370-26ed-11ee-8120-57607de2775b | …
```
=> Add information about shard/thread to the tracing

conn.go, conn_test.go, helpers.go, metadata.go, session.go
iter.Scan provides a poor interface to qerying rows, it requires
callers to allocate a fresh value to scan into and a value for the
initial call. This makes errors not obvious and easy to make. The
scanner interface provides a simpler and more obvious interface to
extract results from queries.
=> remove iter.Scan

CHANGELOG.md, batch_test.go, cassandra_test.go, doc.go, example_batch_test.go, example_lwt_batch_test.go, integration_test.go, session.go, session_test.go
According to issue #1187, I have refactored the Query() method for the batch and implemented the Exec() method for the batch structure to save the general pattern of the query execution, and saved the older method (session.ExecuteBatch()) for backward compatibility. 
This means the batch for now behaves the same way as query.
=> CASSGO-7 Change Batch API to be consistent with Query()

CHANGELOG.md, cluster.go, conn.go, logger.go
This PR removes the global instance of the logger. For now, if the logger in the cluster config is not set, the new approach will set a new instance of the default logger for each session.
Issue: #1766
=> CASSGO-24 Remove global logger

CHANGELOG.md, cassandra_test.go, conn.go, frame.go, marshal.go, metadata.go
This PR removes some features that are marked as "Deprecated".
Such as: 
* global var Timeout limit;
`TimeoutLimit` was removed because it was always equal to 0 and the only condition where it was used was always false by 
default. 
* `MustParseConsistency()` function;
It was removed due to its deprecation.
* `New()` method for `typeInfo{}` interface;
It was removed due to its deprecation. Instead of the removed method, the `typeInfo{}` interface has the 
`NewWithError()` that returns an error instead of panicking.
* View field for the KeyspaceMetadata structure;
Removed because of new and more informative `MaterializedViews` field.
=> CASSGO-12 Remove deprecated features
