apache/cassandra-gocql-driver

AUTHORS
marshal.go
marshal_test.go

Marshal and unmarshal from [big]int <-> string

---

.travis.yml

This patch investigates whether Go 1.4 can be supported.

Support for Go 1.4

---

cluster.go
conn.go
conn_test.go
frame.go
integration.sh
marshal.go
marshal_test.go

Support protocol v3 wire format

---

.travis.yml
integration.sh

Use sudo: false in travis for faster builds

Travis sudo: false

---

cassandra_test.go

Always use createCluster so that passed in options are
setup for all the tests used in cassandra_test.
Fixes #346

Always use createCluster in cassandra_test

---

.travis.yml
cassandra_test.go
integration.sh

Introduce an integration test for authentication

---

conn.go

The caller in exec will reuse the streamID in uniq, ensure that
the stream is only available for use after the caller is done
with it.

Fix a potential race when releasing streams

---

cluster.go
conn.go
frame.go
session.go

Send client side timestamps by default for protocol v3+
Fixes #265

Add with default timestamp support

---

cassandra_test.go

This patch just adds a test case to demonstrate support for the WHERE IN clause.

Test for WHERE IN clause

---

.gitignore
frame.go
frame_test.go
fuzz.go

This contains provions to run go-fuzz and includes some fixes to issues it found.

fuzz fixes

---

frame.go
frame_test.go

When writing frames ensure that we dont write a frame which is
invalid as it is too big, ensure that we dont read a frame which
is too large.

Ensure that frames are not bigger than the max

---

marshal.go
udt_test.go

When using UDT's in a protocol which does not support UDT's
return a more helpful error indicating that protocol version 3
or above should be used.

Return a helpful error when using UDT in proto 2

---

marshal.go
marshal_test.go

This is an updated and an cleared version of PR #302. This version can be merged without #287.

Fix list unmarshaling

---

conn.go

If multiple callers calls closeWithError they can both see
that Closed() return false, then they both call Close() where
only one will win the race, they will then both call close() on
the request channel, causing a panic.
Replace the mutex based closed checks with an atomic compare and
swap and a load to prevent races.
fixes #424

prevent 2 callers closing a connection

---

conn.go
conn_test.go

Try to send the error to the waiting requests so that their
callers will see the correct error before closing the quit
channel.
Ensure that this error is not nil so that exec() will not see
a nil frame.

dont swallow the error from closeWithError

---

conn.go

Make the response channel unbuffered so that there is an
explicit synchronisation point between exec() and recv(), this
prevents a case where a timeout could happend and recv() will still
send a response to the waiting response channel even though the caller
is not receving.
In closeWithError if the error is nil dont send it to waiting callers
because they will try to access the response frame, instead close
the quit channel which will indicate the connection has been closed
and should no longer wait for a response.
Updates #435

conn: ensure that callers unblock correctly

---

conn.go

conn: ensure that stream is within bounds

---

AUTHORS
compressor.go
compressor_test.go

Recent changes to the Snappy import path and removal of errors from Encode.

Update snappy import in SnappyCompressor.

---

conn.go

When exec recvieves an error from recv via call.resp it should release
the stream if it is done with it, but only if the connection was not
closed due to the error. This is to avoid potential issues if a response
comes back on a stream.
fixes #468

conn: release the stream when recieving an error

---

cassandra_test.go
policies.go
session.go

fix tokenaware policy when using session.Bind

---

cass1batch_test.go
cassandra_test.go

Fix test create table

---

marshal.go

Encode the UDT field as null if the struct value is nil. Fixes #501.

---

cassandra_test.go
conn.go
integration.sh

Handle the response frame from UDF queries.
Fixes #500

Fix response handling for UDF queries

---

policies.go

Really sorry that I didn't catch this in #505.

Fix deadlock with HostPoolHostPolicy

---

AUTHORS
conn.go
conn_test.go

Fixes #529
It's not the ideal solution, but without knowing anything about the internals of instaclustr there is no point in doing anything else.

added a list of approved authenticators 

---

conn.go

Use sync.Pool to recycle inflight call requests.
Fixes #446

conn: lazily allocate stream call

---

README.md

Confirm by testing the old link, it will redirect to the new one.

Community project changed repo ownership

---

cassandra_test.go

Ensure that list<map<k, v> can be unmarshalled correctly.
Fixes #557

Check that nested types unmarshal correctly

---

uuid.go
uuid_test.go

uuid: implement text marshalling functions

---

README.md

There was a duplicate link I didn't catch the first time around, this is the second fix.

Community project changed repo ownership 2

---

cluster.go
control.go

Add options to disable registering for status change and topology events
fixes #585 
updates #575

cluster: add option to disable specific events

---

common_test.go

check schema consistency before creating tables

---

events.go
events_ccm_test.go
ring_test.go

update host state after updating the pool

---

cassandra_test.go
conn.go
conn_test.go
frame.go

mock out the stream0 test
updates #581

test: move Stream0 test to conn_test and mock

---

cassandra_test.go
cluster.go
conn.go
frame.go
session.go

Send skip metadata for execute queries which are not CAS queries.
fixes #205

Skip metadata

---

cassandra_test.go
conn_test.go

improve tests to hopefully flake less

Test flakes

---

session.go

Protocol v4 returns the primary key columns for a query on prepare,
so we dont need parse the partition key.

session: use proto 4 pkey columns

---

conn.go

Remove the redundant err != nil check inside the loop and
use call.timeout to check if the caller has gone away.
This fixes the root cause issue of Stream0 test flakes
fixes #581

conn: closeWithError should always try to deliver

---

conn.go
conn_test.go

In conn reuse timeout timers for each call in exec.

conn: recycle call query timeout timers

---

batch_test.go
conn.go

fix batch error propogation

---

policies.go

Chose the least used connection to return for a host, this will better
spread out queries amongst connections, which should help to reduce
stream exhaustion.

conn selection: chose the least used conneciton

---

conn.go

There is a potential race condition in checking that the connection is
started. Remove this check and do a single call to recv to read the
startup response frame, then start the serve loop.

conn: fix startup race

---

policies.go

The connection pool will always give the conn selector a new slice of
conns when the list is updated, it also holds a mutex so SetConns will
not be called concurrently. Replace the mutex protected slice of conns
with an atomic.Value.

conn selection: use copy on write for conn list

---

policies.go

Dont mark a host which has been removed from the policy/pools, this
fixes a race where the pool can remove the policies host, then a query
which is using the host will try to mark the host, which does not exist
in the underlying hostpool, causing a log.Fatalf/panic.
Fix this by checking the policy still has the host we want to mark, and
do so whilst holding the mutex read lock so that the hostpool will not
change.
updates #686

polcies: dont mark a removed host

---

AUTHORS
frame.go
session.go

This is pretty straightforward - needed it to be able to work with a custom QueryHandler C*-side.

Adds parsing / handling for CQLv4 Custom Payload, bytes map, access via Iter

---

README.md

Not sure if there's any criteria for what is put in the ecosphere list. This repo seemed generally useful to me.

Add willfaught/gockle repo ecosphere link

---

metadata.go

PR for issue #708 
Don't think this is the best code, but it fixes the panic.

Get table metadata for materialized views.

---

AUTHORS
events.go
metadata.go

Hey,
Thanks for the lot of work put into this project.
We needed the shcema update feature, so i implemented based on our requirements.
Hope it helps and can be merged (or at least starts a conversation :))

Use server sent events to maintain a client side view of the keyspace schemas #554

---

errors.go
frame.go

tread unknown error codes as a read frame error

frame: add writeFailure error

---

.travis.yml

Travis Trusty builds support Java 1.8
fixes #646

travis: try using trusty beta builds

---

marshal.go

Allow nil maps.

---

AUTHORS
token.go
token_test.go

Fix incorrect random partioner hash function

---

AUTHORS
helpers.go
session.go

Corrects typo and a grammatical mistake (#744)

---

AUTHORS
host_source.go
policies.go
policies_test.go
query_executor.go

Added a nil check before trying to use a host to execute a query.  This was causing nil pointer dereference exceptions as described at https://github.com/gocql/gocql/issues/743. Also made some optimizations to reduce lock scoping in the TokenAwareHostPolicy

Issue 743 Fix

---

AUTHORS
session.go

closes: https://github.com/gocql/gocql/issues/774

Eliminate temporarily leaking goroutine in reconnectDownedHosts

---

events_test.go

This just eliminates the leaking goroutine in events_test

Fix leaking goroutine in events_test.go

---

AUTHORS
marshal.go

Allow nil lists.

---

CONTRIBUTING.md
README.md

update README to match Travis CI

---

host_source.go
session.go

Add Scanner method to Iter which returns a type which allows scanning
result rows in a similar method to that provided by database/sql in the
standard library. This makes it easier to handle and differentiate
Scanning marshalling errors from other errors.
Fixes #681

add iter scanner interface and method

---

helpers.go

Add support for tinyint

---

.travis.yml
cassandra_test.go
integration.sh
metadata.go
metadata_test.go
udt_test.go

travis: update to 3.0

---

cassandra_test.go
cluster.go
conn.go
conn_test.go
control.go
control_test.go
frame.go
ring.go
session.go

Add a method to discover the max protocol version from a list of hosts.
Fixes #540

Add support to discovery protocol version

---

AUTHORS
token.go

avoids panic should all cassandra nodes suddenly "disappear" (i.e. network partition or other)

return nil if there are no tokens (i.e. no hosts available)

---

AUTHORS
cluster.go
conn.go
connectionpool.go
control.go
events.go
frame.go
host_source.go
logger.go
metadata.go
policies.go
session.go

This add a StdLogger interface and a Logger global variable to allow users to change the logger they want to use.
This is the follow up to #833

Custom logger

---

connectionpool.go
session.go

While implementing lazy loading (#730) I made these changes that were independent of the lazy connection changes.  I pulled this out into this PR since they were small and probably good changes regardless of #730.

Some pre-work for lazy loading #730

---

cassandra_test.go
helpers.go

I spent many ours chasing down a bug that turned out to be a feature! To assist future users I've improved the documentation for `MapScan()` and added a new test demonstrating it's proper use.

Improved MapScan() documentation and added new MapScan test

---

cassandra_test.go
cluster.go
conn.go
conn_test.go
connectionpool.go
frame.go
internal/ccm/ccm.go
internal/lru/lru.go
metadata.go
session.go

Just some typo fixes. Detected using https://github.com/client9/misspell

fix a bunch of typos

---

cassandra_test.go
common_test.go
conn.go
connectionpool.go
control.go
control_test.go
events.go
filters.go
filters_test.go
host_source.go
host_source_test.go
policies.go
policies_test.go
ring.go
ring_test.go
session.go
session_connect_test.go
token.go
token_test.go

Revert "GetHosts() is now more version tolerant"

---

helpers.go
marshal.go

fix to support the date type

---

marshal.go

Support date type when inserted.  After that I will make up the test.

Support marshal date type

---

conn.go

conn: dont try to trace if we dont have tracer

---

conn.go
conn_test.go

added DseAuthenticator to list of approved authenticators

---

marshal.go
marshal_test.go

Fix and test for unmarshal date type

---

control.go

Check the parsed host from the remote addr when connecting to the
control conn is a valid parsed IP.
Short circuit the host lookup if the remote addr is a TCPAddr then use
its IP and port.

control: improve addr parsing

---

marshal.go
tuple_test.go

Add support for marshalling/unmarshalling nested tuples via slice, array
and structs.
Also improve tuple handling so they can be used with slices, arrays and
structs for values.

marshal: support nested tuples

---

cassandra_test.go

test: add test to unmarshal null into nil

---

marshal.go
marshal_test.go

marshall: allow unmarshalling into nil byte slice

---

marshal.go
marshal_test.go

marshall: handle time encoded values

---

host_source.go
policies_test.go

Panic in connect address if we are unable to use any host. Improve host
string method to show which address we use.

improve HostInfo ConnectAddress

---

host_source.go

hostinfo: fix rlock reentry

---

cassandra_test.go
conn.go
frame.go

Add NamedValue to support naming query values
fixes #970

support named query values

---

AUTHORS
policies.go

- it wasn't using the lock and causing data races

Fix race condition with tokenAwareHostPolicy SetPartitioner

---

session.go

session: dont send timestamp for LWT ops

---

session.go

Revert "session: dont send timestamp for LWT ops"

---

frame.go

Breaking changes are bad. This fixes things to keep things happy.

Fix breaking change introduced in #983

---

control.go
session.go

control: indicate host up on connect

---

session.go

related: https://github.com/gocql/gocql/issues/1011

Remove HostFilter for supplied hosts

---

frame.go

frame: ensure we copy paging state so it doesnt get overwritten

---

AUTHORS

Add myself to authors

---

frame.go

framer: batches do not support named values

---

connectionpool.go

Don't hold the pools mutex while closing the connections to prevent lock
reenetry from HandlErrors which can be called when the connection errors
while closing.
fixes #1031

connectionpool: fix deadlock on locked drain

---

frame.go

I tried to document `UnsetValue` based on https://datastax.github.io/python-driver/api/cassandra/query.html#cassandra.query.UNSET_VALUE and https://docs.datastax.com/en/developer/nodejs-driver/3.2/features/datatypes/nulls/

Document unset value

---

conn.go

The streamPool is already internally serialized by the Go runtime and
designed for high scalability. But currently retrieval from that pool
is unnecessarily serialized by the Conn.mu instead.
Additionally when the pool is empty, the hold times are even higher,
also this channel allocation for the timeout channel eas in that lock scope.
All of this amounted to enough overhead to make the lock appear in
internal profiles.
Technically the only thing required to be serialized are the accesses to
the Conn.calls map, so limit lock scope to exactly these operations.

reduce Conn.mu hold times

---

session.go

query: add Statement method to return generated statement.

---

conn_test.go

skip TestConnClosedBlocked due to test flake

---

AUTHORS
conn.go

Causes data races
see #1116, #1121, #1103

Revert 1026

---

conn.go
conn_test.go
frame.go

Trying to address https://github.com/gocql/gocql/issues/1137, not sure what's meant by "ProtoVersion + Direction"

Improve ObservedFrameHeader

---

.travis.yml

After the last two merges this was added twice to travis.

Run 3.11 tests once

---

cassandra_test.go
host_source.go
host_source_test.go

cc @Zariel @beltran 
Signed-off-by: Alex Lourie <alex@instaclustr.com>

Fix cassandraVersion.Before() call

---

conn.go

Should fix https://github.com/gocql/gocql/issues/1197

dont trace for internal queries

---

cluster.go

...and obviously working on my Github contributor stats ;)

Fix typo in config documentation

---

query_executor.go

When a query is idempotent or speculation is disabled do not launch a
new goroutine.
When we are speculating don't launch a goroutine to do the speculation
instead do the check in line for results while waiting for a speculation
tick.
This also removes the need to spawn a ticker when speculation is
disabled or the query is non idempotent.
fixes #1239 
updates #1212

reduce number of gourtines used to execute queries

---

control.go

Removing redundant connection + dependant goroutines

---

conn.go

conn: reduce contention

---

helpers.go
marshal.go
marshal_test.go

Enhancing date datatype unmarshal into the string

Enhancement of date datatype

---

control.go

Add non-nil check to old connection in error handler

---

conn.go
control.go
host_source.go

Using hostnames instead of IP addresses in session dial

---

conn.go

Fixing the issue introduced by #1300 

Fix for #1300

---

internal/murmur/murmur_test.go

murmur: fix for 32bit arch

---

host_source.go
topology.go
topology_test.go

```
name                   old time/op    new time/op    delta
Topology_ReplicaMap-8    83.5ms ± 1%    54.0ms ± 1%  -35.29%  (p=0.000 n=8+9)
name                   old alloc/op   new alloc/op   delta
Topology_ReplicaMap-8    5.73MB ± 0%    0.83MB ± 0%  -85.44%  (p=0.000 n=9+8)
name                   old allocs/op  new allocs/op  delta
Topology_ReplicaMap-8     89.2k ± 0%      6.9k ± 0%  -92.22%  (p=0.000 n=10+10)
```

networkTopology: optimise replicaMap slightly

---

AUTHORS
cluster.go
conn.go
connectionpool.go

I'd like to inject net.Dialer from outside of this package.
I added an option to receive net.Dialer in ClusterConfig.

Inject Dialer from ClusterConfig

---

policies.go

Reduce allocs when doing query host selection by pooling rands.
updates #1401

policies: pool rand.Rands

---

token.go
topology.go

Some basic documentation is handy when someone is not as familiar with
the code.
More information can be found at
https://docs.datastax.com/en/dse/6.7/dse-arch/datastax_enterprise/dbArch/archAboutDataDistribute.html

Add documentation for token ring values

---

README.md

Documentation is improved by adding a short section to README.md
As it's a doc fix, I haven't added myself to AUTHORS, let me know if it has to be done.

Added authentication example to readme

---

internal/murmur/murmur_appengine.go
internal/murmur/murmur_unsafe.go

internal/murmur: fix appengine and s390x

---

session.go

Creating a session can take a long time if your cluster is big and
there's latency between you and the cluster. We are seeing it take
~10s to create a session to a 45 node cluster with ~30ms of latency.
This is somewhat related to #1369 and #1429, but this change tries to
do the simplest thing to speed up initial connection without changing
any behavior.

Init host pools in parallel.

---

cassandra_test.go
common_test.go
metadata.go

Fixes https://github.com/gocql/gocql/issues/1524 for materialised views

fix compileMetadata bug for materialized views

---

cassandra_test.go
common_test.go
metadata.go

Fixes https://github.com/gocql/gocql/issues/1526

fix compileMetadata bug for aggregate views

---

control.go
frame.go
marshal.go
metadata.go
token.go

Error messages shouldn't be capitalized.
https://github.com/golang/go/wiki/CodeReviewComments#error-strings

Start errors with lowercase letter

---

common_test.go
conn.go
conn_test.go
connectionpool.go
frame.go
helpers.go
host_source.go
internal/lru/lru_test.go
marshal_test.go
policies.go
prepared_cache.go
ring.go
session.go
session_connect_test.go

This code is not used anywhere.

Remove dead code

---

.travis.yml
conn.go
connectionpool.go
control.go
events.go
host_source.go
install_test_deps.sh
integration_test.go
policies.go
session.go
session_unit_test.go

Connect to peers synchronously until policy is ready

---

topology.go

Replication factor can be zero in normal course of operations.
For example, when one doesn't want a keyspace to be replicated
in the given datacenter, when adding or removing datacenters, etc.
Panicking is harmful since it can bring all instances of a service
down at once. Instead, we just don't update the topology if we can
update it and log that it happened. This will keep existing topology
in case it's set to something broken and the client can continue
running.
In case of network topology strategy, if only one DC has unsupported
replication factor, we just skip it, so that we can run with the valid
DCs.
Fixes https://github.com/gocql/gocql/issues/1388
Fixes https://github.com/scylladb/gocql/issues/71

Fix panic when replication factor is zero

---

.travis.yml
AUTHORS
common_test.go
compressor.go
compressor_test.go
go.mod
go.sum
install_test_deps.sh
integration.sh

Add support for LZ4 compression

---

AUTHORS
conn.go
session.go
session_test.go

Implement missing Batch tracing similar to the current Query tracing

Batch tracing

---

AUTHORS
control.go

Prevent deadlock in Session.Close()

---

events.go

Fixes #1591
Related to yugabyte/yugabyte-db#3090

Ignore events if they're disabled

---

cassandra_test.go
cluster.go
conn.go
conn_test.go
connectionpool.go
control.go
frame.go
frame_test.go
framer_bench_test.go
session.go

These are changes in kiwicom/gocql that are upstreamable. The first commit was submitted separately as #1605, but since some of the other commits depend on it, I included it here as well instead of rebasing the changes (and then needing to rebase back once the other PR is merged).
These are mainly improvements for connections in case of network issues.

Stability improvements

---

marshal_test.go

Suggested at https://github.com/gocql/gocql/pull/1583/files#r774983890

Make TestUnmarshalUDT more readable

---

connectionpool.go

Previously if the `NumConns > 1` there was a race to fill the pool and we only ever marked the host as down if the `startCount == 0` but if 2 connections failed simultaneously there would be a race and not always would the startCount be 0. Therefore we now check whenever filling stops to see if the pool is empty and if so, mark as down.
Fixes #1614

Mark node as down if pool filling failed and pool is empty

---

AUTHORS
conn.go
helpers.go
host_source.go

Hi @martin-sucha ,
I prepared the PR for https://github.com/gocql/gocql/issues/1634
This patch also includes changes from this [PR ](https://github.com/gocql/gocql/pull/1632) at the moment.
Please let me know what you think about this approach.

Propagate right cql ports to address translator implementations

---

.github/workflows/main.yml
README.md
cassandra_test.go

ubuntu-18.04 is not available anymore:
https://github.com/actions/runner-images/issues/6002

Fix CI after ubuntu 18.04 stopped working
